import pytest

from leetcode_py import logged_test

from .helpers import assert_browser_history_operations, run_browser_history_operations
from .solution import BrowserHistory


class TestDesignBrowserHistory:
    @logged_test
    @pytest.mark.parametrize(
        "operations, inputs, expected",
        [
            (
                [
                    "BrowserHistory",
                    "visit",
                    "visit",
                    "visit",
                    "back",
                    "back",
                    "forward",
                    "visit",
                    "forward",
                    "back",
                    "back",
                ],
                [
                    ["leetcode.com"],
                    ["google.com"],
                    ["facebook.com"],
                    ["youtube.com"],
                    [1],
                    [1],
                    [1],
                    ["linkedin.com"],
                    [2],
                    [2],
                    [7],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    "facebook.com",
                    "google.com",
                    "facebook.com",
                    None,
                    "linkedin.com",
                    "google.com",
                    "leetcode.com",
                ],
            ),
            (["BrowserHistory"], [["a.com"]], [None]),
            (["BrowserHistory", "back"], [["home.com"], [100]], [None, "home.com"]),
            (["BrowserHistory", "forward"], [["home.com"], [50]], [None, "home.com"]),
            (
                ["BrowserHistory", "visit", "forward"],
                [["h.com"], ["x.com"], [100]],
                [None, None, "x.com"],
            ),
            (
                ["BrowserHistory", "visit", "back", "visit", "forward"],
                [["h.com"], ["x.com"], [1], ["y.com"], [1]],
                [None, None, "h.com", None, "y.com"],
            ),
            (
                ["BrowserHistory", "visit", "visit", "back", "back", "forward", "forward"],
                [["h.com"], ["a.com"], ["b.com"], [5], [5], [5], [5]],
                [None, None, None, "h.com", "h.com", "b.com", "b.com"],
            ),
            (
                ["BrowserHistory", "visit", "back", "visit", "back", "back"],
                [["h.com"], ["a.com"], [1], ["b.com"], [1], [100]],
                [None, None, "h.com", None, "h.com", "h.com"],
            ),
            (
                ["BrowserHistory", "visit", "visit", "forward", "visit"],
                [["cscj.com"], ["aypfoyf.com"], ["pasznqps.com"], [10], ["er.com"]],
                [None, None, None, "pasznqps.com", None],
            ),
            (
                ["BrowserHistory", "forward", "forward", "forward", "forward", "back"],
                [["usyouucp.com"], [10], [5], [10], [3], [1]],
                [
                    None,
                    "usyouucp.com",
                    "usyouucp.com",
                    "usyouucp.com",
                    "usyouucp.com",
                    "usyouucp.com",
                ],
            ),
            (
                ["BrowserHistory", "forward", "forward", "forward", "back", "forward", "visit"],
                [["secg.com"], [10], [100], [5], [3], [5], ["p.com"]],
                [None, "secg.com", "secg.com", "secg.com", "secg.com", "secg.com", None],
            ),
            (
                ["BrowserHistory", "forward", "visit", "forward", "visit", "visit", "visit"],
                [
                    ["mbslylq.com"],
                    [10],
                    ["zhozgpt.com"],
                    [1],
                    ["zuqhgmnk.com"],
                    ["lsgtlpc.com"],
                    ["ganyzthz.com"],
                ],
                [None, "mbslylq.com", None, "zhozgpt.com", None, None, None],
            ),
            (
                ["BrowserHistory", "visit", "visit", "visit", "visit", "visit", "visit", "visit"],
                [
                    ["cnjhbv.com"],
                    ["ybbgc.com"],
                    ["jw.com"],
                    ["vkvr.com"],
                    ["hjjnvvkr.com"],
                    ["mz.com"],
                    ["wzz.com"],
                    ["gyudhrw.com"],
                ],
                [None, None, None, None, None, None, None, None],
            ),
            (
                ["BrowserHistory", "visit", "visit", "back", "forward", "visit", "forward", "back"],
                [["tfae.com"], ["sc.com"], ["igiw.com"], [1], [100], ["pc.com"], [1], [1]],
                [None, None, None, "sc.com", "igiw.com", None, "pc.com", "igiw.com"],
            ),
            (
                [
                    "BrowserHistory",
                    "visit",
                    "visit",
                    "visit",
                    "forward",
                    "visit",
                    "back",
                    "back",
                    "forward",
                ],
                [
                    ["fjjrxuzg.com"],
                    ["s.com"],
                    ["ny.com"],
                    ["pgdzf.com"],
                    [3],
                    ["ue.com"],
                    [100],
                    [1],
                    [1],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    "pgdzf.com",
                    None,
                    "fjjrxuzg.com",
                    "fjjrxuzg.com",
                    "s.com",
                ],
            ),
            (
                [
                    "BrowserHistory",
                    "back",
                    "back",
                    "forward",
                    "forward",
                    "visit",
                    "back",
                    "forward",
                    "visit",
                    "visit",
                ],
                [
                    ["m.com"],
                    [100],
                    [10],
                    [5],
                    [1],
                    ["cmwcbax.com"],
                    [3],
                    [10],
                    ["ax.com"],
                    ["v.com"],
                ],
                [
                    None,
                    "m.com",
                    "m.com",
                    "m.com",
                    "m.com",
                    None,
                    "m.com",
                    "cmwcbax.com",
                    None,
                    None,
                ],
            ),
            (
                [
                    "BrowserHistory",
                    "back",
                    "forward",
                    "back",
                    "back",
                    "visit",
                    "back",
                    "visit",
                    "forward",
                    "visit",
                    "forward",
                ],
                [
                    ["oqt.com"],
                    [5],
                    [10],
                    [100],
                    [2],
                    ["htzlv.com"],
                    [10],
                    ["f.com"],
                    [1],
                    ["noc.com"],
                    [1],
                ],
                [
                    None,
                    "oqt.com",
                    "oqt.com",
                    "oqt.com",
                    "oqt.com",
                    None,
                    "oqt.com",
                    None,
                    "f.com",
                    None,
                    "noc.com",
                ],
            ),
            (
                [
                    "BrowserHistory",
                    "back",
                    "visit",
                    "visit",
                    "back",
                    "back",
                    "back",
                    "forward",
                    "back",
                    "back",
                    "visit",
                    "visit",
                ],
                [
                    ["sqvacl.com"],
                    [1],
                    ["mfraoimv.com"],
                    ["kjsh.com"],
                    [1],
                    [100],
                    [1],
                    [10],
                    [1],
                    [2],
                    ["ipqaa.com"],
                    ["skvf.com"],
                ],
                [
                    None,
                    "sqvacl.com",
                    None,
                    None,
                    "mfraoimv.com",
                    "sqvacl.com",
                    "sqvacl.com",
                    "kjsh.com",
                    "mfraoimv.com",
                    "sqvacl.com",
                    None,
                    None,
                ],
            ),
        ],
    )
    def test_browser_history(
        self, operations: list[str], inputs: list[list], expected: list[str | None]
    ):
        result, _ = run_browser_history_operations(BrowserHistory, operations, inputs)
        assert_browser_history_operations(result, expected)
