import pytest

from leetcode_py import logged_test

from .helpers import assert_traffic_light, run_traffic_light
from .solution import TrafficLight


class TestTrafficLightControlledIntersection:
    @logged_test
    @pytest.mark.parametrize(
        "operations, inputs, expected",
        [
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [[], [1, 1, 2], [3, 1, 1], [5, 1, 2], [2, 2, 4], [4, 2, 3]],
                [
                    "Car 1 Has Passed Road A In Direction 2",
                    "Car 3 Has Passed Road A In Direction 1",
                    "Car 5 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 2 Has Passed Road B In Direction 4",
                    "Car 4 Has Passed Road B In Direction 3",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [[], [1, 1, 2], [2, 2, 4], [3, 2, 3], [5, 1, 1], [4, 2, 3]],
                [
                    "Car 1 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 2 Has Passed Road B In Direction 4",
                    "Car 3 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 5 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 4 Has Passed Road B In Direction 3",
                ],
            ),
            (
                ["TrafficLight", "car_arrived"],
                [[], [1, 1, 2]],
                ["Car 1 Has Passed Road A In Direction 2"],
            ),
            (
                ["TrafficLight", "car_arrived"],
                [[], [7, 2, 3]],
                ["Traffic Light On Road B Is Green", "Car 7 Has Passed Road B In Direction 3"],
            ),
            (
                ["TrafficLight", "car_arrived", "car_arrived", "car_arrived", "car_arrived"],
                [[], [1, 1, 1], [2, 1, 2], [3, 1, 1], [4, 1, 2]],
                [
                    "Car 1 Has Passed Road A In Direction 1",
                    "Car 2 Has Passed Road A In Direction 2",
                    "Car 3 Has Passed Road A In Direction 1",
                    "Car 4 Has Passed Road A In Direction 2",
                ],
            ),
            (
                ["TrafficLight", "car_arrived", "car_arrived", "car_arrived", "car_arrived"],
                [[], [5, 2, 3], [6, 2, 4], [7, 2, 3], [8, 2, 4]],
                [
                    "Traffic Light On Road B Is Green",
                    "Car 5 Has Passed Road B In Direction 3",
                    "Car 6 Has Passed Road B In Direction 4",
                    "Car 7 Has Passed Road B In Direction 3",
                    "Car 8 Has Passed Road B In Direction 4",
                ],
            ),
            (
                ["TrafficLight", "car_arrived", "car_arrived", "car_arrived", "car_arrived"],
                [[], [1, 1, 2], [2, 2, 3], [3, 1, 1], [4, 2, 4]],
                [
                    "Car 1 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 2 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 3 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 4 Has Passed Road B In Direction 4",
                ],
            ),
            (
                ["TrafficLight", "car_arrived", "car_arrived", "car_arrived", "car_arrived"],
                [[], [9, 2, 4], [8, 1, 1], [7, 2, 3], [6, 1, 2]],
                [
                    "Traffic Light On Road B Is Green",
                    "Car 9 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 8 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 7 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 6 Has Passed Road A In Direction 2",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [[], [1, 1, 1], [2, 1, 2], [3, 2, 3], [4, 1, 1], [5, 1, 2]],
                [
                    "Car 1 Has Passed Road A In Direction 1",
                    "Car 2 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 3 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 4 Has Passed Road A In Direction 1",
                    "Car 5 Has Passed Road A In Direction 2",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [[], [6, 2, 4], [7, 2, 3], [8, 1, 2], [9, 2, 4], [10, 2, 3]],
                [
                    "Traffic Light On Road B Is Green",
                    "Car 6 Has Passed Road B In Direction 4",
                    "Car 7 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 8 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 9 Has Passed Road B In Direction 4",
                    "Car 10 Has Passed Road B In Direction 3",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [
                    [],
                    [1, 1, 1],
                    [2, 2, 4],
                    [3, 1, 1],
                    [4, 2, 4],
                    [5, 1, 1],
                    [6, 2, 4],
                    [7, 1, 1],
                    [8, 2, 4],
                    [9, 1, 1],
                    [10, 2, 4],
                    [11, 1, 1],
                    [12, 2, 4],
                    [13, 1, 1],
                    [14, 2, 4],
                    [15, 1, 1],
                ],
                [
                    "Car 1 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 2 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 3 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 4 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 5 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 6 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 7 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 8 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 9 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 10 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 11 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 12 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 13 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 14 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 15 Has Passed Road A In Direction 1",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [
                    [],
                    [1, 1, 1],
                    [2, 1, 2],
                    [3, 1, 1],
                    [4, 1, 2],
                    [5, 1, 1],
                    [6, 1, 2],
                    [7, 1, 1],
                    [8, 1, 2],
                    [9, 1, 1],
                    [10, 1, 2],
                    [11, 1, 1],
                    [12, 1, 2],
                    [13, 1, 1],
                    [14, 1, 2],
                    [15, 1, 1],
                    [16, 1, 2],
                    [17, 1, 1],
                    [18, 1, 2],
                    [19, 1, 1],
                    [20, 1, 2],
                ],
                [
                    "Car 1 Has Passed Road A In Direction 1",
                    "Car 2 Has Passed Road A In Direction 2",
                    "Car 3 Has Passed Road A In Direction 1",
                    "Car 4 Has Passed Road A In Direction 2",
                    "Car 5 Has Passed Road A In Direction 1",
                    "Car 6 Has Passed Road A In Direction 2",
                    "Car 7 Has Passed Road A In Direction 1",
                    "Car 8 Has Passed Road A In Direction 2",
                    "Car 9 Has Passed Road A In Direction 1",
                    "Car 10 Has Passed Road A In Direction 2",
                    "Car 11 Has Passed Road A In Direction 1",
                    "Car 12 Has Passed Road A In Direction 2",
                    "Car 13 Has Passed Road A In Direction 1",
                    "Car 14 Has Passed Road A In Direction 2",
                    "Car 15 Has Passed Road A In Direction 1",
                    "Car 16 Has Passed Road A In Direction 2",
                    "Car 17 Has Passed Road A In Direction 1",
                    "Car 18 Has Passed Road A In Direction 2",
                    "Car 19 Has Passed Road A In Direction 1",
                    "Car 20 Has Passed Road A In Direction 2",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [
                    [],
                    [1, 1, 2],
                    [2, 2, 3],
                    [3, 1, 2],
                    [4, 2, 3],
                    [5, 1, 2],
                    [6, 2, 3],
                    [7, 1, 2],
                    [8, 2, 3],
                    [9, 1, 2],
                    [10, 2, 3],
                    [11, 1, 2],
                    [12, 2, 3],
                    [13, 1, 2],
                    [14, 2, 3],
                    [15, 1, 2],
                    [16, 2, 3],
                    [17, 1, 2],
                    [18, 2, 3],
                    [19, 1, 2],
                    [20, 2, 3],
                ],
                [
                    "Car 1 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 2 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 3 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 4 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 5 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 6 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 7 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 8 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 9 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 10 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 11 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 12 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 13 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 14 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 15 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 16 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 17 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 18 Has Passed Road B In Direction 3",
                    "Traffic Light On Road A Is Green",
                    "Car 19 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 20 Has Passed Road B In Direction 3",
                ],
            ),
            (
                [
                    "TrafficLight",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                    "car_arrived",
                ],
                [[], [1, 1, 2], [2, 1, 1], [3, 2, 3], [4, 2, 4], [5, 1, 1], [6, 1, 2], [7, 2, 4]],
                [
                    "Car 1 Has Passed Road A In Direction 2",
                    "Car 2 Has Passed Road A In Direction 1",
                    "Traffic Light On Road B Is Green",
                    "Car 3 Has Passed Road B In Direction 3",
                    "Car 4 Has Passed Road B In Direction 4",
                    "Traffic Light On Road A Is Green",
                    "Car 5 Has Passed Road A In Direction 1",
                    "Car 6 Has Passed Road A In Direction 2",
                    "Traffic Light On Road B Is Green",
                    "Car 7 Has Passed Road B In Direction 4",
                ],
            ),
        ],
    )
    def test_car_arrived(self, operations: list[str], inputs: list[list[int]], expected: list[str]):
        result, _ = run_traffic_light(TrafficLight, operations, inputs)
        assert_traffic_light(result, expected)
