tag_name = "grind"

problems_list = [
    (1, "Two Sum"),
    (20, "Valid Parentheses"),
    (21, "Merge Two Sorted Lists"),
    (121, "Best Time to Buy and Sell Stock"),
    (125, "Valid Palindrome"),
    (226, "Invert Binary Tree"),
    (242, "Valid Anagram"),
    (704, "Binary Search"),
    (733, "Flood Fill"),
    (235, "Lowest Common Ancestor of a Binary Search Tree"),
    (110, "Balanced Binary Tree"),
    (141, "Linked List Cycle"),
    (232, "Implement Queue using Stacks"),
    (278, "First Bad Version"),
    (383, "Ransom Note"),
    (70, "Climbing Stairs"),
    (409, "Longest Palindrome"),
    (206, "Reverse Linked List"),
    (169, "Majority Element"),
    (67, "Add Binary"),
    (543, "Diameter of Binary Tree"),
    (876, "Middle of the Linked List"),
    (104, "Maximum Depth of Binary Tree"),
    (217, "Contains Duplicate"),
    (252, "Meeting Rooms"),
    (13, "Roman to Integer"),
    (844, "Backspace String Compare"),
    (338, "Counting Bits"),
    (100, "Same Tree"),
    (191, "Number of 1 Bits"),
    (14, "Longest Common Prefix"),
    (136, "Single Number"),
    (234, "Palindrome Linked List"),
    (283, "Move Zeroes"),
    (101, "Symmetric Tree"),
    (268, "Missing Number"),
    (9, "Palindrome Number"),
    (108, "Convert Sorted Array to Binary Search Tree"),
    (190, "Reverse Bits"),
    (572, "Subtree of Another Tree"),
    (977, "Squares of a Sorted Array"),
    (53, "Maximum Subarray"),
    (57, "Insert Interval"),
    (542, "01 Matrix"),
    (973, "K Closest Points to Origin"),
    (3, "Longest Substring Without Repeating Characters"),
    (15, "3Sum"),
    (102, "Binary Tree Level Order Traversal"),
    (133, "Clone Graph"),
    (150, "Evaluate Reverse Polish Notation"),
    (207, "Course Schedule"),
    (208, "Implement Trie (Prefix Tree)"),
    (322, "Coin Change"),
    (238, "Product of Array Except Self"),
    (155, "Min Stack"),
    (98, "Validate Binary Search Tree"),
    (200, "Number of Islands"),
    (994, "Rotting Oranges"),
    (33, "Search in Rotated Sorted Array"),
    (39, "Combination Sum"),
    (46, "Permutations"),
    (56, "Merge Intervals"),
    (236, "Lowest Common Ancestor of a Binary Tree"),
    (981, "Time Based Key-Value Store"),
    (721, "Accounts Merge"),
    (75, "Sort Colors"),
    (139, "Word Break"),
    (416, "Partition Equal Subset Sum"),
    (8, "String to Integer (atoi)"),
    (54, "Spiral Matrix"),
    (78, "Subsets"),
    (199, "Binary Tree Right Side View"),
    (5, "Longest Palindromic Substring"),
    (62, "Unique Paths"),
    (105, "Construct Binary Tree from Preorder and Inorder Traversal"),
    (11, "Container With Most Water"),
    (17, "Letter Combinations of a Phone Number"),
    (79, "Word Search"),
    (438, "Find All Anagrams in a String"),
    (310, "Minimum Height Trees"),
    (621, "Task Scheduler"),
    (146, "LRU Cache"),
    (230, "Kth Smallest Element in a BST"),
    (739, "Daily Temperatures"),
    (198, "House Robber"),
    (134, "Gas Station"),
    (31, "Next Permutation"),
    (36, "Valid Sudoku"),
    (49, "Group Anagrams"),
    (152, "Maximum Product Subarray"),
    (211, "Design Add and Search Words Data Structure"),
    (417, "Pacific Atlantic Water Flow"),
    (19, "Remove Nth Node From End of List"),
    (1091, "Shortest Path to Get Food"),
    (287, "Find the Duplicate Number"),
    (692, "Top K Frequent Words"),
    (300, "Longest Increasing Subsequence"),
    (261, "Graph Valid Tree"),
    (210, "Course Schedule II"),
    (24, "Swap Nodes in Pairs"),
    (113, "Path Sum II"),
    (128, "Longest Consecutive Sequence"),
    (189, "Rotate Array"),
    (328, "Odd Even Linked List"),
    (394, "Decode String"),
    (525, "Contiguous Array"),
    (662, "Maximum Width of Binary Tree"),
    (658, "Find K Closest Elements"),
    (424, "Longest Repeating Character Replacement"),
    (285, "Inorder Successor in BST"),
    (55, "Jump Game"),
    (2, "Add Two Numbers"),
    (22, "Generate Parentheses"),
    (148, "Sort List"),
    (323, "Number of Connected Components in an Undirected Graph"),
    (1197, "Minimum Knight Moves"),
    (560, "Subarray Sum Equals K"),
    (735, "Asteroid Collision"),
    (528, "Random Pick with Weight"),
    (215, "Kth Largest Element in an Array"),
    (221, "Maximal Square"),
    (48, "Rotate Image"),
    (103, "Binary Tree Zigzag Level Order Traversal"),
    (362, "Design Hit Counter"),
    (437, "Path Sum III"),
    (50, "Pow(x, n)"),
    (74, "Search a 2D Matrix"),
    (179, "Largest Number"),
    (91, "Decode Ways"),
    (253, "Meeting Rooms II"),
    (7, "Reverse Integer"),
    (73, "Set Matrix Zeroes"),
    (143, "Reorder List"),
    (271, "Encode and Decode Strings"),
    (787, "Cheapest Flights Within K Stops"),
    (863, "All Nodes Distance K in Binary Tree"),
    (16, "3Sum Closest"),
    (61, "Rotate List"),
    (153, "Find Minimum in Rotated Sorted Array"),
    (227, "Basic Calculator II"),
    (377, "Combination Sum IV"),
    (380, "Insert Delete GetRandom O(1)"),
    (435, "Non-overlapping Intervals"),
    (76, "Minimum Window Substring"),
    (297, "Serialize and Deserialize Binary Tree"),
    (42, "Trapping Rain Water"),
    (295, "Find Median from Data Stream"),
    (127, "Word Ladder"),
    (224, "Basic Calculator"),
    (1235, "Maximum Profit in Job Scheduling"),
    (23, "Merge k Sorted Lists"),
    (84, "Largest Rectangle in Histogram"),
    (124, "Binary Tree Maximum Path Sum"),
    (895, "Maximum Frequency Stack"),
    (4, "Median of Two Sorted Arrays"),
    (329, "Longest Increasing Path in a Matrix"),
    (32, "Longest Valid Parentheses"),
    (588, "Design In-Memory File System"),
    (759, "Employee Free Time"),
    (212, "Word Search II"),
    (269, "Alien Dictionary"),
    (815, "Bus Routes"),
    (239, "Sliding Window Maximum"),
    (336, "Palindrome Pairs"),
    (25, "Reverse Nodes in k-Group"),
    (37, "Sudoku Solver"),
    (41, "First Missing Positive"),
    (51, "N-Queens"),
    (632, "Smallest Range Covering Elements from K Lists"),
]
