tag_name = "neetcode-250"

problems_list = [
    (1929, "Concatenation of Array"),
    (217, "Contains Duplicate"),
    (242, "Valid Anagram"),
    (1, "Two Sum"),
    (14, "Longest Common Prefix"),
    (49, "Group Anagrams"),
    (27, "Remove Element"),
    (169, "Majority Element"),
    (705, "Design HashSet"),
    (706, "Design HashMap"),
    (912, "Sort an Array"),
    (75, "Sort Colors"),
    (347, "Top K Frequent Elements"),
    (271, "Encode and Decode Strings"),
    (304, "Range Sum Query 2D Immutable"),
    (238, "Product of Array Except Self"),
    (36, "Valid Sudoku"),
    (128, "Longest Consecutive Sequence"),
    (122, "Best Time to Buy And Sell Stock II"),
    (229, "Majority Element II"),
    (560, "Subarray Sum Equals K"),
    (41, "First Missing Positive"),
    (344, "Reverse String"),
    (125, "Valid Palindrome"),
    (680, "Valid Palindrome II"),
    (1768, "Merge Strings Alternately"),
    (88, "Merge Sorted Array"),
    (26, "Remove Duplicates From Sorted Array"),
    (167, "Two Sum II Input Array Is Sorted"),
    (15, "3Sum"),
    (18, "4Sum"),
    (189, "Rotate Array"),
    (11, "Container With Most Water"),
    (881, "Boats to Save People"),
    (42, "Trapping Rain Water"),
    (219, "Contains Duplicate II"),
    (121, "Best Time to Buy And Sell Stock"),
    (3, "Longest Substring Without Repeating Characters"),
    (424, "Longest Repeating Character Replacement"),
    (567, "Permutation In String"),
    (209, "Minimum Size Subarray Sum"),
    (658, "Find K Closest Elements"),
    (76, "Minimum Window Substring"),
    (239, "Sliding Window Maximum"),
    (682, "Baseball Game"),
    (20, "Valid Parentheses"),
    (225, "Implement Stack Using Queues"),
    (232, "Implement Queue using Stacks"),
    (155, "Min Stack"),
    (150, "Evaluate Reverse Polish Notation"),
    (22, "Generate Parentheses"),
    (735, "Asteroid Collision"),
    (739, "Daily Temperatures"),
    (901, "Online Stock Span"),
    (853, "Car Fleet"),
    (71, "Simplify Path"),
    (394, "Decode String"),
    (895, "Maximum Frequency Stack"),
    (84, "Largest Rectangle In Histogram"),
    (704, "Binary Search"),
    (35, "Search Insert Position"),
    (374, "Guess Number Higher Or Lower"),
    (69, "Sqrt(x)"),
    (74, "Search a 2D Matrix"),
    (875, "Koko Eating Bananas"),
    (1011, "Capacity to Ship Packages Within D Days"),
    (153, "Find Minimum In Rotated Sorted Array"),
    (33, "Search In Rotated Sorted Array"),
    (81, "Search In Rotated Sorted Array II"),
    (981, "Time Based Key Value Store"),
    (410, "Split Array Largest Sum"),
    (4, "Median of Two Sorted Arrays"),
    (1095, "Find in Mountain Array"),
    (206, "Reverse Linked List"),
    (21, "Merge Two Sorted Lists"),
    (141, "Linked List Cycle"),
    (143, "Reorder List"),
    (19, "Remove Nth Node From End of List"),
    (138, "Copy List With Random Pointer"),
    (2, "Add Two Numbers"),
    (287, "Find The Duplicate Number"),
    (92, "Reverse Linked List II"),
    (622, "Design Circular Queue"),
    (146, "LRU Cache"),
    (460, "LFU Cache"),
    (23, "Merge K Sorted Lists"),
    (25, "Reverse Nodes In K Group"),
    (94, "Binary Tree Inorder Traversal"),
    (144, "Binary Tree Preorder Traversal"),
    (145, "Binary Tree Postorder Traversal"),
    (226, "Invert Binary Tree"),
    (104, "Maximum Depth of Binary Tree"),
    (543, "Diameter of Binary Tree"),
    (110, "Balanced Binary Tree"),
    (100, "Same Tree"),
    (572, "Subtree of Another Tree"),
    (235, "Lowest Common Ancestor of a Binary Search Tree"),
    (701, "Insert into a Binary Search Tree"),
    (450, "Delete Node in a BST"),
    (102, "Binary Tree Level Order Traversal"),
    (199, "Binary Tree Right Side View"),
    (427, "Construct Quad Tree"),
    (1448, "Count Good Nodes In Binary Tree"),
    (98, "Validate Binary Search Tree"),
    (230, "Kth Smallest Element In a Bst"),
    (105, "Construct Binary Tree From Preorder And Inorder Traversal"),
    (337, "House Robber III"),
    (1325, "Delete Leaves With a Given Value"),
    (124, "Binary Tree Maximum Path Sum"),
    (297, "Serialize And Deserialize Binary Tree"),
    (703, "Kth Largest Element In a Stream"),
    (1046, "Last Stone Weight"),
    (973, "K Closest Points to Origin"),
    (215, "Kth Largest Element In An Array"),
    (621, "Task Scheduler"),
    (355, "Design Twitter"),
    (1834, "Single Threaded CPU"),
    (767, "Reorganize String"),
    (1405, "Longest Happy String"),
    (1094, "Car Pooling"),
    (295, "Find Median From Data Stream"),
    (502, "IPO"),
    (1863, "Sum of All Subsets XOR Total"),
    (78, "Subsets"),
    (39, "Combination Sum"),
    (40, "Combination Sum II"),
    (77, "Combinations"),
    (46, "Permutations"),
    (90, "Subsets II"),
    (47, "Permutations II"),
    (79, "Word Search"),
    (131, "Palindrome Partitioning"),
    (17, "Letter Combinations of a Phone Number"),
    (473, "Matchsticks to Square"),
    (698, "Partition to K Equal Sum Subsets"),
    (51, "N Queens"),
    (52, "N Queens II"),
    (140, "Word Break II"),
    (208, "Implement Trie Prefix Tree"),
    (211, "Design Add And Search Words Data Structure"),
    (2707, "Extra Characters in a String"),
    (212, "Word Search II"),
    (463, "Island Perimeter"),
    (953, "Verifying An Alien Dictionary"),
    (997, "Find the Town Judge"),
    (200, "Number of Islands"),
    (695, "Max Area of Island"),
    (133, "Clone Graph"),
    (286, "Walls And Gates"),
    (994, "Rotting Oranges"),
    (417, "Pacific Atlantic Water Flow"),
    (130, "Surrounded Regions"),
    (752, "Open The Lock"),
    (207, "Course Schedule"),
    (210, "Course Schedule II"),
    (261, "Graph Valid Tree"),
    (1462, "Course Schedule IV"),
    (323, "Number of Connected Components In An Undirected Graph"),
    (684, "Redundant Connection"),
    (721, "Accounts Merge"),
    (399, "Evaluate Division"),
    (310, "Minimum Height Trees"),
    (127, "Word Ladder"),
    (1631, "Path with Minimum Effort"),
    (743, "Network Delay Time"),
    (332, "Reconstruct Itinerary"),
    (1584, "Min Cost to Connect All Points"),
    (778, "Swim In Rising Water"),
    (269, "Alien Dictionary"),
    (787, "Cheapest Flights Within K Stops"),
    (1489, "Find Critical and Pseudo Critical Edges in Minimum Spanning Tree"),
    (2392, "Build a Matrix With Conditions"),
    (2709, "Greatest Common Divisor Traversal"),
    (70, "Climbing Stairs"),
    (746, "Min Cost Climbing Stairs"),
    (1137, "N-th Tribonacci Number"),
    (198, "House Robber"),
    (213, "House Robber II"),
    (5, "Longest Palindromic Substring"),
    (647, "Palindromic Substrings"),
    (91, "Decode Ways"),
    (322, "Coin Change"),
    (152, "Maximum Product Subarray"),
    (139, "Word Break"),
    (300, "Longest Increasing Subsequence"),
    (416, "Partition Equal Subset Sum"),
    (377, "Combination Sum IV"),
    (279, "Perfect Squares"),
    (343, "Integer Break"),
    (1406, "Stone Game III"),
    (62, "Unique Paths"),
    (63, "Unique Paths II"),
    (64, "Minimum Path Sum"),
    (1143, "Longest Common Subsequence"),
    (1049, "Last Stone Weight II"),
    (309, "Best Time to Buy And Sell Stock With Cooldown"),
    (518, "Coin Change II"),
    (494, "Target Sum"),
    (97, "Interleaving String"),
    (877, "Stone Game"),
    (1140, "Stone Game II"),
    (329, "Longest Increasing Path In a Matrix"),
    (115, "Distinct Subsequences"),
    (72, "Edit Distance"),
    (312, "Burst Balloons"),
    (10, "Regular Expression Matching"),
    (860, "Lemonade Change"),
    (53, "Maximum Subarray"),
    (918, "Maximum Sum Circular Subarray"),
    (978, "Longest Turbulent Subarray"),
    (55, "Jump Game"),
    (45, "Jump Game II"),
    (1871, "Jump Game VII"),
    (134, "Gas Station"),
    (846, "Hand of Straights"),
    (649, "Dota2 Senate"),
    (1899, "Merge Triplets to Form Target Triplet"),
    (763, "Partition Labels"),
    (678, "Valid Parenthesis String"),
    (135, "Candy"),
    (57, "Insert Interval"),
    (56, "Merge Intervals"),
    (435, "Non Overlapping Intervals"),
    (252, "Meeting Rooms"),
    (253, "Meeting Rooms II"),
    (2402, "Meeting Rooms III"),
    (1851, "Minimum Interval to Include Each Query"),
    (168, "Excel Sheet Column Title"),
    (1071, "Greatest Common Divisor of Strings"),
    (2807, "Insert Greatest Common Divisors in Linked List"),
    (867, "Transpose Matrix"),
    (48, "Rotate Image"),
    (54, "Spiral Matrix"),
    (73, "Set Matrix Zeroes"),
    (202, "Happy Number"),
    (66, "Plus One"),
    (13, "Roman to Integer"),
    (50, "Pow(x, n)"),
    (43, "Multiply Strings"),
    (2013, "Detect Squares"),
    (136, "Single Number"),
    (191, "Number of 1 Bits"),
    (338, "Counting Bits"),
    (67, "Add Binary"),
    (190, "Reverse Bits"),
    (268, "Missing Number"),
    (371, "Sum of Two Integers"),
    (7, "Reverse Integer"),
    (201, "Bitwise AND of Numbers Range"),
    (3133, "Minimum Array End"),
]
