tag_name = "neetcode"

problems_list = [
    (1, "Two Sum"),
    (2, "Add Two Numbers"),
    (3, "Longest Substring Without Repeating Characters"),
    (4, "Median of Two Sorted Arrays"),
    (5, "Longest Palindromic Substring"),
    (6, "Zigzag Conversion"),
    (7, "Reverse Integer"),
    (9, "Palindrome Number"),
    (10, "Regular Expression Matching"),
    (11, "Container With Most Water"),
    (12, "Integer to Roman"),
    (13, "Roman to Integer"),
    (14, "Longest Common Prefix"),
    (15, "3Sum"),
    (17, "Letter Combinations of a Phone Number"),
    (18, "4Sum"),
    (19, "Remove Nth Node From End of List"),
    (20, "Valid Parentheses"),
    (21, "Merge Two Sorted Lists"),
    (22, "Generate Parentheses"),
    (23, "Merge K Sorted Lists"),
    (24, "Swap Nodes In Pairs"),
    (25, "Reverse Nodes In K Group"),
    (26, "Remove Duplicates From Sorted Array"),
    (27, "Remove Element"),
    (28, "Find The Index of The First Occurrence in a String"),
    (31, "Next Permutation"),
    (33, "Search In Rotated Sorted Array"),
    (34, "Find First And Last Position of Element In Sorted Array"),
    (35, "Search Insert Position"),
    (36, "Valid Sudoku"),
    (39, "Combination Sum"),
    (40, "Combination Sum II"),
    (41, "First Missing Positive"),
    (42, "Trapping Rain Water"),
    (43, "Multiply Strings"),
    (45, "Jump Game II"),
    (46, "Permutations"),
    (47, "Permutations II"),
    (48, "Rotate Image"),
    (49, "Group Anagrams"),
    (50, "Pow(x, n)"),
    (51, "N Queens"),
    (52, "N Queens II"),
    (53, "Maximum Subarray"),
    (54, "Spiral Matrix"),
    (55, "Jump Game"),
    (56, "Merge Intervals"),
    (57, "Insert Interval"),
    (58, "Length of Last Word"),
    (59, "Spiral Matrix II"),
    (61, "Rotate List"),
    (62, "Unique Paths"),
    (63, "Unique Paths II"),
    (64, "Minimum Path Sum"),
    (66, "Plus One"),
    (67, "Add Binary"),
    (68, "Text Justification"),
    (69, "Sqrt(x)"),
    (70, "Climbing Stairs"),
    (71, "Simplify Path"),
    (72, "Edit Distance"),
    (73, "Set Matrix Zeroes"),
    (74, "Search a 2D Matrix"),
    (75, "Sort Colors"),
    (76, "Minimum Window Substring"),
    (77, "Combinations"),
    (78, "Subsets"),
    (79, "Word Search"),
    (80, "Remove Duplicates From Sorted Array II"),
    (81, "Search In Rotated Sorted Array II"),
    (83, "Remove Duplicates From Sorted List"),
    (84, "Largest Rectangle In Histogram"),
    (86, "Partition List"),
    (88, "Merge Sorted Array"),
    (90, "Subsets II"),
    (91, "Decode Ways"),
    (92, "Reverse Linked List II"),
    (93, "Restore IP Addresses"),
    (94, "Binary Tree Inorder Traversal"),
    (95, "Unique Binary Search Trees II"),
    (96, "Unique Binary Search Trees"),
    (97, "Interleaving String"),
    (98, "Validate Binary Search Tree"),
    (99, "Recover Binary Search Tree"),
    (100, "Same Tree"),
    (101, "Symmetric Tree"),
    (102, "Binary Tree Level Order Traversal"),
    (103, "Binary Tree Zigzag Level Order Traversal"),
    (104, "Maximum Depth of Binary Tree"),
    (105, "Construct Binary Tree From Preorder And Inorder Traversal"),
    (106, "Construct Binary Tree from Inorder and Postorder Traversal"),
    (108, "Convert Sorted Array to Binary Search Tree"),
    (110, "Balanced Binary Tree"),
    (112, "Path Sum"),
    (115, "Distinct Subsequences"),
    (116, "Populating Next Right Pointers In Each Node"),
    (118, "Pascals Triangle"),
    (119, "Pascal's Triangle II"),
    (120, "Triangle"),
    (121, "Best Time to Buy And Sell Stock"),
    (122, "Best Time to Buy And Sell Stock II"),
    (124, "Binary Tree Maximum Path Sum"),
    (125, "Valid Palindrome"),
    (127, "Word Ladder"),
    (128, "Longest Consecutive Sequence"),
    (129, "Sum Root to Leaf Numbers"),
    (130, "Surrounded Regions"),
    (131, "Palindrome Partitioning"),
    (133, "Clone Graph"),
    (134, "Gas Station"),
    (135, "Candy"),
    (136, "Single Number"),
    (138, "Copy List With Random Pointer"),
    (139, "Word Break"),
    (140, "Word Break II"),
    (141, "Linked List Cycle"),
    (143, "Reorder List"),
    (144, "Binary Tree Preorder Traversal"),
    (145, "Binary Tree Postorder Traversal"),
    (146, "LRU Cache"),
    (147, "Insertion Sort List"),
    (148, "Sort List"),
    (149, "Maximum Points on a Line"),
    (150, "Evaluate Reverse Polish Notation"),
    (152, "Maximum Product Subarray"),
    (153, "Find Minimum In Rotated Sorted Array"),
    (155, "Min Stack"),
    (156, "Binary Tree Upside Down"),
    (159, "Longest Substring with At Most Two Distinct Characters"),
    (160, "Intersection of Two Linked Lists"),
    (161, "One Edit Distance"),
    (162, "Find Peak Element"),
    (163, "Missing Ranges"),
    (167, "Two Sum II Input Array Is Sorted"),
    (168, "Excel Sheet Column Title"),
    (169, "Majority Element"),
    (173, "Binary Search Tree Iterator"),
    (179, "Largest Number"),
    (186, "Reverse Words in a String II"),
    (187, "Repeated DNA Sequences"),
    (189, "Rotate Array"),
    (190, "Reverse Bits"),
    (191, "Number of 1 Bits"),
    (198, "House Robber"),
    (199, "Binary Tree Right Side View"),
    (200, "Number of Islands"),
    (201, "Bitwise AND of Numbers Range"),
    (202, "Happy Number"),
    (203, "Remove Linked List Elements"),
    (204, "Count Primes"),
    (205, "Isomorphic Strings"),
    (206, "Reverse Linked List"),
    (207, "Course Schedule"),
    (208, "Implement Trie Prefix Tree"),
    (209, "Minimum Size Subarray Sum"),
    (210, "Course Schedule II"),
    (211, "Design Add And Search Words Data Structure"),
    (212, "Word Search II"),
    (213, "House Robber II"),
    (214, "Shortest Palindrome"),
    (215, "Kth Largest Element In An Array"),
    (217, "Contains Duplicate"),
    (219, "Contains Duplicate II"),
    (221, "Maximal Square"),
    (225, "Implement Stack Using Queues"),
    (226, "Invert Binary Tree"),
    (227, "Basic Calculator II"),
    (229, "Majority Element II"),
    (230, "Kth Smallest Element In a Bst"),
    (231, "Power of Two"),
    (232, "Implement Queue using Stacks"),
    (234, "Palindrome Linked List"),
    (235, "Lowest Common Ancestor of a Binary Search Tree"),
    (236, "Lowest Common Ancestor of a Binary Tree"),
    (238, "Product of Array Except Self"),
    (239, "Sliding Window Maximum"),
    (241, "Different Ways to Add Parentheses"),
    (242, "Valid Anagram"),
    (243, "Shortest Word Distance"),
    (244, "Shortest Word Distance II"),
    (246, "Strobogrammatic Number"),
    (247, "Strobogrammatic Number II"),
    (249, "Group Shifted Strings"),
    (250, "Count Univalue Subtrees"),
    (252, "Meeting Rooms"),
    (253, "Meeting Rooms II"),
    (254, "Factor Combinations"),
    (255, "Verify Preorder Sequence in Binary Search Tree"),
    (256, "Paint House"),
    (259, "3Sum Smaller"),
    (260, "Single Number III"),
    (261, "Graph Valid Tree"),
    (263, "Ugly Number"),
    (264, "Ugly Number II"),
    (265, "Paint House II"),
    (266, "Palindrome Permutation"),
    (268, "Missing Number"),
    (269, "Alien Dictionary"),
    (270, "Closest Binary Search Tree Value"),
    (271, "Encode and Decode Strings"),
    (272, "Closest Binary Search Tree Value II"),
    (273, "Integer to English Words"),
    (276, "Paint Fence"),
    (277, "Find the Celebrity"),
    (279, "Perfect Squares"),
    (280, "Wiggle Sort"),
    (281, "Zigzag Iterator"),
    (283, "Move Zeroes"),
    (286, "Walls And Gates"),
    (287, "Find The Duplicate Number"),
    (290, "Word Pattern"),
    (291, "Word Pattern II"),
    (295, "Find Median From Data Stream"),
    (296, "Best Meeting Point"),
    (297, "Serialize And Deserialize Binary Tree"),
    (298, "Binary Tree Longest Consecutive Sequence"),
    (300, "Longest Increasing Subsequence"),
    (303, "Range Sum Query - Immutable"),
    (304, "Range Sum Query 2D Immutable"),
    (305, "Number of Islands II"),
    (308, "Range Sum Query 2D - Mutable"),
    (309, "Best Time to Buy And Sell Stock With Cooldown"),
    (310, "Minimum Height Trees"),
    (311, "Sparse Matrix Multiplication"),
    (312, "Burst Balloons"),
    (314, "Binary Tree Vertical Order Traversal"),
    (317, "Shortest Distance from All Buildings"),
    (322, "Coin Change"),
    (323, "Number of Connected Components In An Undirected Graph"),
    (329, "Longest Increasing Path In a Matrix"),
    (332, "Reconstruct Itinerary"),
    (333, "Largest BST Subtree"),
    (337, "House Robber III"),
    (338, "Counting Bits"),
    (339, "Nested List Weight Sum"),
    (340, "Longest Substring with At Most K Distinct Characters"),
    (341, "Flatten Nested List Iterator"),
    (342, "Power of Four"),
    (343, "Integer Break"),
    (344, "Reverse String"),
    (346, "Moving Average from Data Stream"),
    (347, "Top K Frequent Elements"),
    (348, "Design Tic-Tac-Toe"),
    (349, "Intersection of Two Arrays"),
    (351, "Android Unlock Patterns"),
    (352, "Data Stream as Disjoint Intervals"),
    (353, "Design Snake Game"),
    (354, "Russian Doll Envelopes"),
    (355, "Design Twitter"),
    (356, "Line Reflection"),
    (358, "Rearrange String k Distance Apart"),
    (359, "Logger Rate Limiter"),
    (360, "Sort Transformed Array"),
    (362, "Design Hit Counter"),
    (364, "Nested List Weight Sum II"),
    (366, "Find Leaves of Binary Tree"),
    (367, "Valid Perfect Square"),
    (368, "Largest Divisible Subset"),
    (369, "Plus One Linked List"),
    (371, "Sum of Two Integers"),
    (374, "Guess Number Higher Or Lower"),
    (377, "Combination Sum IV"),
    (379, "Design Phone Directory"),
    (380, "Insert Delete Get Random O(1)"),
    (383, "Ransom Note"),
    (386, "Lexicographical Numbers"),
    (387, "First Unique Character in a String"),
    (389, "Find the Difference"),
    (392, "Is Subsequence"),
    (394, "Decode String"),
    (399, "Evaluate Division"),
    (402, "Remove K Digits"),
    (407, "Trapping Rain Water II"),
    (408, "Valid Word Abbreviation"),
    (409, "Longest Palindrome"),
    (410, "Split Array Largest Sum"),
    (416, "Partition Equal Subset Sum"),
    (417, "Pacific Atlantic Water Flow"),
    (418, "Sentence Screen Fitting"),
    (422, "Valid Word Square"),
    (424, "Longest Repeating Character Replacement"),
    (426, "Convert Binary Search Tree to Sorted Doubly Linked List"),
    (427, "Construct Quad Tree"),
    (428, "Serialize and Deserialize N-ary Tree"),
    (431, "Encode N-ary Tree to Binary Tree"),
    (435, "Non Overlapping Intervals"),
    (438, "Find All Anagrams in a String"),
    (439, "Ternary Expression Parser"),
    (440, "K-th Smallest in Lexicographical Order"),
    (441, "Arranging Coins"),
    (442, "Find All Duplicates in an Array"),
    (443, "String Compression"),
    (444, "Sequence Reconstruction"),
    (445, "Add Two Numbers II"),
    (446, "Arithmetic Slices II"),
    (448, "Find All Numbers Disappeared in An Array"),
    (450, "Delete Node in a BST"),
    (451, "Sort Characters By Frequency"),
    (452, "Minimum Number of Arrows to Burst Balloons"),
    (455, "Assign Cookies"),
    (456, "132 Pattern"),
    (460, "LFU Cache"),
    (463, "Island Perimeter"),
    (465, "Optimal Account Balancing"),
    (471, "Encode String with Shortest Length"),
    (472, "Concatenated Words"),
    (473, "Matchsticks to Square"),
    (474, "Ones and Zeroes"),
    (484, "Find Permutation"),
    (485, "Max Consecutive Ones"),
    (487, "Max Consecutive Ones II"),
    (489, "Robot Room Cleaner"),
    (490, "The Maze"),
    (494, "Target Sum"),
    (496, "Next Greater Element I"),
    (499, "The Maze III"),
    (502, "IPO"),
    (505, "The Maze II"),
    (510, "Inorder Successor in BST II"),
    (513, "Find Bottom Left Tree Value"),
    (514, "Freedom Trail"),
    (515, "Find Largest Value in Tree Row"),
    (516, "Longest Palindromic Subsequence"),
    (518, "Coin Change II"),
    (523, "Continuous Subarray Sum"),
    (525, "Contiguous Array"),
    (528, "Random Pick with Weight"),
    (531, "Lonely Pixel I"),
    (535, "Encode and Decode TinyURL"),
    (538, "Convert Bst to Greater Tree"),
    (539, "Minimum Time Difference"),
    (540, "Single Element in a Sorted Array"),
    (543, "Diameter of Binary Tree"),
    (545, "Boundary of Binary Tree"),
    (547, "Number of Provinces"),
    (549, "Binary Tree Longest Consecutive Sequence II"),
    (552, "Student Attendance Record II"),
    (554, "Brick Wall"),
    (555, "Split Concatenated Strings"),
    (557, "Reverse Words in a String III"),
    (560, "Subarray Sum Equals K"),
    (567, "Permutation In String"),
    (572, "Subtree of Another Tree"),
    (576, "Out of Boundary Paths"),
    (582, "Kill Process"),
    (588, "Design In-Memory File System"),
    (590, "N-ary Tree Postorder Traversal"),
    (604, "Design Compressed String Iterator"),
    (605, "Can Place Flowers"),
    (606, "Construct String From Binary Tree"),
    (616, "Add Bold Tag in String"),
    (617, "Merge Two Binary Trees"),
    (621, "Task Scheduler"),
    (622, "Design Circular Queue"),
    (624, "Maximum Distance in Arrays"),
    (625, "Minimum Factorization"),
    (629, "K Inverse Pairs Array"),
    (631, "Design Excel Sum Formula"),
    (632, "Smallest Range Covering Elements from K Lists"),
    (633, "Sum of Square Numbers"),
    (635, "Design Log Storage System"),
    (642, "Design Search Autocomplete System"),
    (644, "Maximum Average Subarray II"),
    (645, "Set Mismatch"),
    (646, "Maximum Length of Pair Chain"),
    (647, "Palindromic Substrings"),
    (649, "Dota2 Senate"),
    (650, "2 Keys Keyboard"),
    (651, "4 Keys Keyboard"),
    (652, "Find Duplicate Subtrees"),
    (656, "Coin Path"),
    (658, "Find K Closest Elements"),
    (661, "Image Smoother"),
    (662, "Maximum Width of Binary Tree"),
    (665, "Non Decreasing Array"),
    (669, "Trim a Binary Search Tree"),
    (670, "Maximum Swap"),
    (673, "Number of Longest Increasing Subsequence"),
    (678, "Valid Parenthesis String"),
    (680, "Valid Palindrome II"),
    (682, "Baseball Game"),
    (684, "Redundant Connection"),
    (689, "Maximum Sum of 3 Non-Overlapping Subarrays"),
    (691, "Stickers to Spell Word"),
    (694, "Number of Distinct Islands"),
    (695, "Max Area of Island"),
    (698, "Partition to K Equal Sum Subsets"),
    (701, "Insert into a Binary Search Tree"),
    (703, "Kth Largest Element In a Stream"),
    (704, "Binary Search"),
    (705, "Design HashSet"),
    (706, "Design HashMap"),
    (707, "Design Linked List"),
    (708, "Insert into a Sorted Circular Linked List"),
    (711, "Number of Distinct Islands II"),
    (713, "Subarray Product Less Than K"),
    (716, "Max Stack"),
    (719, "Find K-th Smallest Pair Distance"),
    (721, "Accounts Merge"),
    (723, "Candy Crush"),
    (724, "Find Pivot Index"),
    (725, "Split Linked List in Parts"),
    (726, "Number of Atoms"),
    (729, "My Calendar I"),
    (731, "My Calendar II"),
    (733, "Flood Fill"),
    (734, "Sentence Similarity"),
    (735, "Asteroid Collision"),
    (737, "Sentence Similarity II"),
    (739, "Daily Temperatures"),
    (740, "Delete And Earn"),
    (741, "Cherry Pickup"),
    (743, "Network Delay Time"),
    (746, "Min Cost Climbing Stairs"),
    (751, "IP to CIDR"),
    (752, "Open The Lock"),
    (759, "Employee Free Time"),
    (760, "Find Anagram Mappings"),
    (763, "Partition Labels"),
    (767, "Reorganize String"),
    (769, "Max Chunks To Make Sorted"),
    (772, "Basic Calculator III"),
    (773, "Sliding Puzzle"),
    (774, "Minimize Max Distance to Gas Station"),
    (778, "Swim In Rising Water"),
    (779, "K-th Symbol in Grammar"),
    (783, "Minimum Distance between BST Nodes"),
    (785, "Is Graph Bipartite?"),
    (787, "Cheapest Flights Within K Stops"),
    (791, "Custom Sort String"),
    (799, "Champagne Tower"),
    (802, "Find Eventual Safe States"),
    (805, "Split Array With Same Average"),
    (815, "Bus Routes"),
    (827, "Making A Large Island"),
    (837, "New 21 Game"),
    (838, "Push Dominoes"),
    (840, "Magic Squares In Grid"),
    (844, "Backspace String Compare"),
    (846, "Hand of Straights"),
    (853, "Car Fleet"),
    (857, "Minimum Cost to Hire K Workers"),
    (860, "Lemonade Change"),
    (861, "Score After Flipping Matrix"),
    (862, "Shortest Subarray with Sum at Least K"),
    (867, "Transpose Matrix"),
    (872, "Leaf-Similar Trees"),
    (873, "Length of Longest Fibonacci Subsequence"),
    (874, "Walking Robot Simulation"),
    (875, "Koko Eating Bananas"),
    (876, "Middle of the Linked List"),
    (877, "Stone Game"),
    (879, "Profitable Schemes"),
    (881, "Boats to Save People"),
    (884, "Uncommon Words from Two Sentences"),
    (885, "Spiral Matrix III"),
    (889, "Construct Binary Tree from Preorder and Postorder Traversal"),
    (894, "All Possible Full Binary Trees"),
    (895, "Maximum Frequency Stack"),
    (896, "Monotonic Array"),
    (901, "Online Stock Span"),
    (904, "Fruit into Basket"),
    (905, "Sort Array by Parity"),
    (907, "Sum of Subarray Minimums"),
    (909, "Snakes And Ladders"),
    (912, "Sort an Array"),
    (916, "Word Subsets"),
    (918, "Maximum Sum Circular Subarray"),
    (920, "Number of Music Playlists"),
    (921, "Minimum Add to Make Parentheses Valid"),
    (926, "Flip String to Monotone Increasing"),
    (929, "Unique Email Addresses"),
    (930, "Binary Subarrays with Sum"),
    (931, "Minimum Falling Path Sum"),
    (934, "Shortest Bridge"),
    (935, "Knight Dialer"),
    (938, "Range Sum of BST"),
    (945, "Minimum Increment to Make Array Unique"),
    (946, "Validate Stack Sequences"),
    (948, "Bag of Tokens"),
    (950, "Reveal Cards In Increasing Order"),
    (951, "Flip Equivalent Binary Trees"),
    (953, "Verifying An Alien Dictionary"),
    (958, "Check Completeness of a Binary Tree"),
    (959, "Regions Cut By Slashes"),
    (962, "Maximum Width Ramp"),
    (973, "K Closest Points to Origin"),
    (974, "Subarray Sums Divisible by K"),
    (977, "Squares of a Sorted Array"),
    (978, "Longest Turbulent Subarray"),
    (979, "Distribute Coins in Binary Tree"),
    (981, "Time Based Key Value Store"),
    (983, "Minimum Cost For Tickets"),
    (986, "Interval List Intersections"),
    (988, "Smallest String Starting From Leaf"),
    (989, "Add to Array-Form of Integer"),
    (992, "Subarrays with K Different Integers"),
    (994, "Rotting Oranges"),
    (995, "Minimum Number of K Consecutive Bit Flips"),
    (997, "Find the Town Judge"),
    (1002, "Find Common Characters"),
    (1004, "Max Consecutive Ones III"),
    (1011, "Capacity to Ship Packages Within D Days"),
    (1014, "Best Sightseeing Pair"),
    (1020, "Number of Enclaves"),
    (1028, "Recover a Tree From Preorder Traversal"),
    (1029, "Two City Scheduling"),
    (1035, "Uncrossed Lines"),
    (1041, "Robot Bounded In Circle"),
    (1043, "Partition Array for Maximum Sum"),
    (1046, "Last Stone Weight"),
    (1048, "Longest String Chain"),
    (1049, "Last Stone Weight II"),
    (1051, "Height Checker"),
    (1052, "Grumpy Bookstore Owner"),
    (1055, "Shortest Way to Form String"),
    (1056, "Confusing Number"),
    (1057, "Campus Bikes"),
    (1059, "All Paths from Source Lead to Destination"),
    (1060, "Missing Element in Sorted Array"),
    (1071, "Greatest Common Divisor of Strings"),
    (1072, "Flip Columns For Maximum Number of Equal Rows"),
    (1074, "Number of Submatrices that Sum to Target"),
    (1079, "Letter Tile Possibilities"),
    (1086, "High Five"),
    (1087, "Brace Expansion"),
    (1091, "Shortest Path in Binary Matrix"),
    (1092, "Shortest Common Supersequence"),
    (1094, "Car Pooling"),
    (1095, "Find in Mountain Array"),
    (1099, "Two Sum Less Than K"),
    (1100, "Find K-Length Substrings With No Repeated Characters"),
    (1101, "The Earliest Moment When Everyone Become Friends"),
    (1102, "Path With Maximum Minimum Value"),
    (1105, "Filling Bookcase Shelves"),
    (1106, "Parsing A Boolean Expression"),
    (1110, "Delete Nodes And Return Forest"),
    (1120, "Maximum Average Subtree"),
    (1122, "Relative Sort Array"),
    (1129, "Shortest Path with Alternating Colors"),
    (1133, "Largest Unique Number"),
    (1134, "Armstrong Number"),
    (1136, "Parallel Courses"),
    (1137, "N-th Tribonacci Number"),
    (1140, "Stone Game II"),
    (1143, "Longest Common Subsequence"),
    (1150, "Check If a Number Is Majority Element in a Sorted Array"),
    (1152, "Analyze User Website Visit Pattern"),
    (1155, "Number of Dice Rolls with Target Sum"),
    (1160, "Find Words That Can Be Formed by Characters"),
    (1162, "As Far from Land as Possible"),
    (1165, "Single-Row Keyboard"),
    (1166, "Design File System"),
    (1167, "Minimum Cost to Connect Sticks"),
    (1180, "Count Substrings with Only One Distinct Letter"),
    (1183, "Maximum Number of Ones"),
    (1189, "Maximum Number of Balloons"),
    (1190, "Reverse Substrings Between Each Pair of Parentheses"),
    (1196, "How Many Apples Can You Put into the Basket"),
    (1197, "Minimum Knight Moves"),
    (1198, "Find Smallest Common Element in All Rows"),
    (1208, "Get Equal Substrings Within Budget"),
    (1209, "Remove All Adjacent Duplicates In String II"),
    (1214, "Two Sum BSTs"),
    (1216, "Valid Palindrome III"),
    (1219, "Path with Maximum Gold"),
    (1220, "Count Vowels Permutation"),
    (1228, "Missing Number In Arithmetic Progression"),
    (1229, "Meeting Scheduler"),
    (1231, "Divide Chocolate"),
    (1233, "Remove Sub-Folders from the Filesystem"),
    (1235, "Maximum Profit in Job Scheduling"),
    (1236, "Web Crawler"),
    (1239, "Maximum Length of a Concatenated String With Unique Characters"),
    (1243, "Array Transformation"),
    (1244, "Design A Leaderboard"),
    (1245, "Tree Diameter"),
    (1248, "Count Number of Nice Subarrays"),
    (1249, "Minimum Remove to Make Valid Parentheses"),
    (1254, "Number of Closed Islands"),
    (1255, "Maximum Score Words Formed By Letters"),
    (1258, "Synonymous Sentences"),
    (1259, "Handshakes That Don't Cross"),
    (1260, "Shift 2D Grid"),
    (1265, "Print Immutable Linked List in Reverse"),
    (1267, "Count Servers that Communicate"),
    (1268, "Search Suggestions System"),
    (1269, "Number of Ways to Stay in the Same Place After Some Steps"),
    (1272, "Remove Interval"),
    (1274, "Number of Ships in a Rectangle"),
    (1277, "Count Square Submatrices with All Ones"),
    (1288, "Remove Covered Intervals"),
    (1289, "Minimum Falling Path Sum II"),
    (1291, "Sequential Digits"),
    (1299, "Replace Elements With Greatest Element On Right Side"),
    (1310, "XOR Queries of a Subarray"),
    (1325, "Delete Leaves With a Given Value"),
    (1334, "Find the City With the Smallest Number of Neighbors at a Threshold Distance"),
    (1335, "Minimum Difficulty of a Job Schedule"),
    (1343, "Number of Sub Arrays of Size K and Avg Greater than or Equal to Threshold"),
    (1358, "Number of Substrings Containing All Three Characters"),
    (1359, "Count all Valid Pickup and Delivery Options"),
    (1361, "Validate Binary Tree Nodes"),
    (1367, "Linked List in Binary Tree"),
    (1368, "Minimum Cost to Make at Least One Valid Path in a Grid"),
    (1371, "Find the Longest Substring Containing Vowels in Even Counts"),
    (1376, "Time Needed to Inform All Employees"),
    (1380, "Lucky Numbers in a Matrix"),
    (1383, "Maximum Performance of a Team"),
    (1394, "Find Lucky Integer in an Array"),
    (1395, "Count Number of Teams"),
    (1396, "Design Underground System"),
    (1400, "Construct K Palindrome Strings"),
    (1405, "Longest Happy String"),
    (1406, "Stone Game III"),
    (1408, "String Matching in an Array"),
    (1415, "The k-th Lexicographical String of All Happy Strings of Length n"),
    (1422, "Maximum Score After Splitting a String"),
    (1423, "Maximum Points You Can Obtain From Cards"),
    (1425, "Constrained Subsequence Sum"),
    (1426, "Counting Elements"),
    (1427, "Perform String Shifts"),
    (1428, "Leftmost Column With at Least a One"),
    (1429, "First Unique Number"),
    (1436, "Destination City"),
    (1438, "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit"),
    (1442, "Count Triplets That Can Form Two Arrays of Equal XOR"),
    (1443, "Minimum Time to Collect All Apples in a Tree"),
    (1448, "Count Good Nodes In Binary Tree"),
    (1456, "Maximum Number of Vowels in a Substring of Given Length"),
    (1457, "Pseudo-Palindromic Paths in a Binary Tree"),
    (1460, "Make Two Arrays Equal by Reversing Subarrays"),
    (1461, "Check if a String Contains all Binary Codes of Size K"),
    (1462, "Course Schedule IV"),
    (1463, "Cherry Pickup II"),
    (1466, "Reorder Routes to Make All Paths Lead to The City Zero"),
    (1470, "Shuffle the Array"),
    (1472, "Design Browser History"),
    (1474, "Delete N Nodes After M Nodes of a Linked List"),
    (1475, "Final Prices With a Special Discount in a Shop"),
    (1481, "Least Number of Unique Integers after K Removal"),
    (1489, "Find Critical and Pseudo Critical Edges in Minimum Spanning Tree"),
    (1490, "Clone N-ary Tree"),
    (1496, "Path Crossing"),
    (1498, "Number of Subsequences That Satisfy The Given Sum Condition"),
    (1506, "Find Root of N-Ary Tree"),
    (1508, "Range Sum of Sorted Subarray Sums"),
    (1509, "Minimum Difference Between Largest and Smallest Value in Three Moves"),
    (1512, "Number of Good Pairs"),
    (1514, "Path with Maximum Probability"),
    (1518, "Water Bottles"),
    (1522, "Diameter of N-Ary Tree"),
    (1523, "Count Odd Numbers in an Interval Range"),
    (1524, "Number of Sub-arrays With Odd Sum"),
    (1526, "Minimum Number of Increments on Subarrays to Form a Target Array"),
    (1530, "Number of Good Leaf Nodes Pairs"),
    (1531, "String Compression II"),
    (1533, "Find the Index of the Large Integer"),
    (1538, "Guess the Majority in a Hidden Array"),
    (1544, "Make The String Great"),
    (1545, "Find Kth Bit in Nth Binary String"),
    (1547, "Minimum Cost to Cut a Stick"),
    (1553, "Minimum Number of Days to Eat N Oranges"),
    (1557, "Minimum Number of Vertices to Reach all Nodes"),
    (1564, "Put Boxes Into the Warehouse I"),
    (1568, "Minimum Number of Days to Disconnect Island"),
    (1570, "Dot Product of Two Sparse Vectors"),
    (1572, "Matrix Diagonal Sum"),
    (1574, "Shortest Subarray to be Removed to Make Array Sorted"),
    (1578, "Minimum Time To Make Rope Colorful"),
    (1579, "Remove Max Number of Edges to Keep Graph Fully Traversable"),
    (1584, "Min Cost to Connect All Points"),
    (1590, "Make Sum Divisible by P"),
    (1593, "Split a String Into the Max Number of Unique Substrings"),
    (1598, "Crawler Log Folder"),
    (1603, "Design Parking System"),
    (1605, "Find Valid Matrix Given Row and Column Sums"),
    (1608, "Special Array with X Elements Greater than or Equal X"),
    (1609, "Even Odd Tree"),
    (1611, "Minimum Number of One Bit Operations to Make Integers Zero"),
    (1614, "Maximum Nesting Depth of the Parentheses"),
    (1624, "Largest Substring Between Two Equal Characters"),
    (1626, "Best Team with no Conflicts"),
    (1631, "Path with Minimum Effort"),
    (1636, "Sort Array by Increasing Frequency"),
    (1637, "Wildest Vertical Area Between Two Points Containing No Points"),
    (1639, "Number of Ways to Form a Target String Given a Dictionary"),
    (1642, "Furthest Building You Can Reach"),
    (1647, "Minimum Deletions to Make Character Frequencies Unique"),
    (1650, "Lowest Common Ancestor of a Binary Tree III"),
    (1652, "Defuse the Bomb"),
    (1653, "Minimum Deletions to Make String Balanced"),
    (1658, "Minimum Operations to Reduce X to Zero"),
    (1662, "Check If Two String Arrays are Equivalent"),
    (1669, "Merge in Between Linked Lists"),
    (1671, "Minimum Number of Removals to Make Mountain Array"),
    (1675, "Minimize Deviation in Array"),
    (1684, "Count the Number of Consistent Strings"),
    (1685, "Sum of Absolute Differences in a Sorted Array"),
    (1688, "Count of Matches in Tournament"),
    (1700, "Number of Students Unable to Eat Lunch"),
    (1701, "Average Waiting Time"),
    (1716, "Calculate Money in Leetcode Bank"),
    (1717, "Maximum Score From Removing Substrings"),
    (1718, "Construct the Lexicographically Largest Valid Sequence"),
    (1721, "Swapping Nodes in a Linked List"),
    (1726, "Tuple with Same Product"),
    (1727, "Largest Submatrix With Rearrangements"),
    (1749, "Maximum Absolute Sum of Any Subarray"),
    (1750, "Minimum Length of String after Deleting Similar Ends"),
    (1752, "Check if Array Is Sorted and Rotated"),
    (1758, "Minimum Changes To Make Alternating Binary String"),
    (1760, "Minimum Limit of Balls in a Bag"),
    (1762, "Buildings With an Ocean View"),
    (1768, "Merge Strings Alternately"),
    (1769, "Minimum Number of Operations to Move All Balls to Each Box"),
    (1780, "Check if Number is a Sum of Powers of Three"),
    (1790, "Check if One String Swap Can Make Strings Equal"),
    (1793, "Maximum Score of a Good Subarray"),
    (1799, "Maximize Score after N Operations"),
    (1800, "Maximum Ascending Subarray Sum"),
    (1813, "Sentence Similarity III"),
    (1822, "Sign of the Product of an Array"),
    (1823, "Find the Winner of the Circular Game"),
    (1829, "Maximum XOR for Each Query"),
    (1834, "Single Threaded CPU"),
    (1836, "Remove Duplicates From an Unsorted Linked List"),
    (1838, "Frequency of The Most Frequent Element"),
    (1845, "Seat Reservation Manager"),
    (1846, "Maximum Element After Decreasing and Rearranging"),
    (1849, "Splitting a String Into Descending Consecutive Values"),
    (1851, "Minimum Interval to Include Each Query"),
    (1856, "Maximum Subarray Min Product"),
    (1857, "Largest Color Value in a Directed Graph"),
    (1861, "Rotating the Box"),
    (1863, "Sum of All Subsets XOR Total"),
    (1866, "Number of Ways to Rearrange Sticks With K Sticks Visible"),
    (1868, "Product of Two Run Length Encoded Arrays"),
    (1871, "Jump Game VII"),
    (1882, "Process Tasks Using Servers"),
    (1888, "Minimum Number of Flips to Make The Binary String Alternating"),
    (1891, "Cutting Ribbons"),
    (1897, "Redistribute Characters to Make All Strings Equal"),
    (1898, "Maximum Number of Removable Characters"),
    (1899, "Merge Triplets to Form Target Triplet"),
    (1903, "Largest Odd Number in String"),
    (1905, "Count Sub Islands"),
    (1911, "Maximum Alternating Subsequence Sum"),
    (1913, "Maximum Product Difference Between Two Pairs"),
    (1921, "Eliminate Maximum Number of Monsters"),
    (1929, "Concatenation of Array"),
    (1930, "Unique Length 3 Palindromic Subsequences"),
    (1937, "Maximum Number of Points with Cost"),
    (1942, "The Number of the Smallest Unoccupied Chair"),
    (1944, "Number of Visible People in a Queue"),
    (1958, "Check if Move Is Legal"),
    (1963, "Minimum Number of Swaps to Make The String Balanced"),
    (1964, "Find the Longest Valid Obstacle Course at Each Position"),
    (1966, "Binary Searchable Numbers in an Unsorted Array"),
    (1968, "Array With Elements Not Equal to Average of Neighbors"),
    (1975, "Maximum Matrix Sum"),
    (1976, "Number of Ways to Arrive at Destination"),
    (1980, "Find Unique Binary String"),
    (1984, "Minimum Difference Between Highest And Lowest of K Scores"),
    (1985, "Find The Kth Largest Integer In The Array"),
    (1993, "Operations On Tree"),
    (2001, "Number of Pairs of Interchangeable Rectangles"),
    (2002, "Maximum Product of The Length of Two Palindromic Subsequences"),
    (2009, "Minimum Number of Operations to Make Array Continuous"),
    (2013, "Detect Squares"),
    (2017, "Grid Game"),
    (2021, "Brightest Position on Street"),
    (2022, "Convert 1D Array Into 2D Array"),
    (2028, "Find Missing Observations"),
    (2033, "Minimum Operations to Make a Uni-Value Grid"),
    (2037, "Minimum Number of Moves to Seat Everyone"),
    (2038, "Remove Colored Pieces if Both Neighbors are the Same Color"),
    (2040, "Kth Smallest Product of Two Sorted Arrays"),
    (2044, "Count Number of Maximum Bitwise-OR Subsets"),
    (2045, "Second Minimum Time to Reach Destination"),
    (2050, "Parallel Courses III"),
    (2053, "Kth Distinct String in an Array"),
    (2058, "Find the Minimum and Maximum Number of Nodes Between Critical Points"),
    (2064, "Minimized Maximum of Products Distributed to Any Store"),
    (2070, "Most Beautiful Item for Each Query"),
    (2073, "Time Needed to Buy Tickets"),
    (2092, "Find All People With Secret"),
    (2096, "Step-By-Step Directions From a Binary Tree Node to Another"),
    (2101, "Detonate the Maximum Bombs"),
    (2108, "Find First Palindromic String in the Array"),
    (2109, "Adding Spaces to a String"),
    (2115, "Find All Possible Recipes from Given Supplies"),
    (2116, "Check if a Parentheses String Can Be Valid"),
    (2125, "Number of Laser Beams in a Bank"),
    (2127, "Maximum Employees to Be Invited to a Meeting"),
    (2130, "Maximum Twin Sum Of A Linked List"),
    (2134, "Minimum Swaps to Group All 1's Together II"),
    (2140, "Solving Questions With Brainpower"),
    (2147, "Number of Ways to Divide a Long Corridor"),
    (2149, "Rearrange Array Elements by Sign"),
    (2161, "Partition Array According to Given Pivot"),
    (2181, "Merge Nodes in Between Zeros"),
    (2182, "Construct String With Repeat Limit"),
    (2185, "Counting Words With a Given Prefix"),
    (2191, "Sort the Jumbled Numbers"),
    (2196, "Create Binary Tree From Descriptions"),
    (2206, "Divide Array Into Equal Pairs"),
    (2215, "Find the Difference of Two Arrays"),
    (2218, "Maximum Value of K Coins from Piles"),
    (2220, "Minimum Bit Flips to Convert Number"),
    (2226, "Maximum Candies Allocated to K Children"),
    (2251, "Number of Flowers in Full Bloom"),
    (2257, "Count Unguarded Cells in the Grid"),
    (2264, "Largest 3-Same-Digit Number in String"),
    (2270, "Number of Ways to Split Array"),
    (2275, "Largest Combination With Bitwise AND Greater Than Zero"),
    (2285, "Maximum Total Importance of Roads"),
    (2290, "Minimum Obstacle Removal to Reach Corner"),
    (2300, "Successful Pairs of Spells and Potions"),
    (2306, "Naming a Company"),
    (2326, "Spiral Matrix IV"),
    (2331, "Evaluate Boolean Binary Tree"),
    (2348, "Number of Zero-Filled Subarrays"),
    (2353, "Design a Food Rating System"),
    (2359, "Find Closest Node to Given Two Nodes"),
    (2364, "Count Number of Bad Pairs"),
    (2369, "Check if There is a Valid Partition For The Array"),
    (2370, "Longest Ideal Subsequence"),
    (2373, "Largest Local Values in a Matrix"),
    (2375, "Construct Smallest Number From DI String"),
    (2379, "Minimum Recolors to Get K Consecutive Black Blocks"),
    (2381, "Shifting Letters II"),
    (2390, "Removing Stars From a String"),
    (2392, "Build a Matrix With Conditions"),
    (2393, "Count Strictly Increasing Subarrays"),
    (2401, "Longest Nice Subarray"),
    (2402, "Meeting Rooms III"),
    (2405, "Optimal Partition of String"),
    (2406, "Divide Intervals Into Minimum Number of Groups"),
    (2415, "Reverse Odd Levels of Binary Tree"),
    (2416, "Sum of Prefix Scores of Strings"),
    (2418, "Sort the People"),
    (2419, "Longest Subarray With Maximum Bitwise AND"),
    (2421, "Number of Good Paths"),
    (2425, "Bitwise XOR of All Pairings"),
    (2429, "Minimize XOR"),
    (2439, "Minimize Maximum of Array"),
    (2460, "Apply Operations to an Array"),
    (2461, "Maximum Sum of Distinct Subarrays With Length K"),
    (2466, "Count Ways to Build Good Strings"),
    (2467, "Most Profitable Path in a Tree"),
    (2471, "Minimum Number of Operations to Sort a Binary Tree by Level"),
    (2477, "Minimum Fuel Cost to Report to the Capital"),
    (2483, "Minimum Penalty for a Shop"),
    (2486, "Append Characters to String to Make Subsequence"),
    (2487, "Remove Nodes From Linked List"),
    (2490, "Circular Sentence"),
    (2491, "Divide Players Into Teams of Equal Skill"),
    (2492, "Minimum Score of a Path Between Two Cities"),
    (2493, "Divide Nodes Into the Maximum Number of Groups"),
    (2503, "Maximum Number of Points From Grid Queries"),
    (2516, "Take K of Each Character From Left and Right"),
    (2523, "Closest Prime Numbers in Range"),
    (2530, "Maximal Score After Applying K Operations"),
    (2534, "Time Taken to Cross the Door"),
    (2542, "Maximum Subsequence Score"),
    (2551, "Put Marbles in Bags"),
    (2558, "Take Gifts From the Richest Pile"),
    (2559, "Count Vowel Strings in Ranges"),
    (2560, "House Robber IV"),
    (2563, "Count the Number of Fair Pairs"),
    (2570, "Merge Two 2D Arrays by Summing Values"),
    (2577, "Minimum Time to Visit a Cell In a Grid"),
    (2579, "Count Total Number of Colored Cells"),
    (2583, "Kth Largest Sum in a Binary Tree"),
    (2594, "Minimum Time to Repair Cars"),
    (2597, "The Number of Beautiful Subsets"),
    (2601, "Prime Subtraction Operation"),
    (2610, "Convert an Array Into a 2D Array With Conditions"),
    (2616, "Minimize the Maximum Difference of Pairs"),
    (2641, "Cousins in Binary Tree II"),
    (2658, "Maximum Number of Fish in a Grid"),
    (2678, "Number of Senior Citizens"),
    (2683, "Neighboring Bitwise XOR"),
    (2685, "Count the Number of Complete Components"),
    (2696, "Minimum String Length After Removing Substrings"),
    (2698, "Find the Punishment Number of an Integer"),
    (2706, "Buy Two Chocolates"),
    (2707, "Extra Characters in a String"),
    (2709, "Greatest Common Divisor Traversal"),
    (2742, "Painting the Walls"),
    (2751, "Robot Collisions"),
    (2779, "Maximum Beauty of an Array After Applying Operation"),
    (2780, "Minimum Index of a Valid Split"),
    (2807, "Insert Greatest Common Divisors in Linked List"),
    (2812, "Find the Safest Path in a Grid"),
    (2818, "Apply Operations to Maximize Score"),
    (2864, "Maximum Odd Binary Number"),
    (2870, "Minimum Number of Operations to Make Array Empty"),
    (2872, "Maximum Number of K-Divisible Components"),
    (2914, "Minimum Number of Changes to Make Binary String Beautiful"),
    (2924, "Find Champion II"),
    (2929, "Distribute Candies Among Children II"),
    (2938, "Separate Black and White Balls"),
    (2940, "Find Building Where Alice and Bob Can Meet"),
    (2948, "Make Lexicographically Smallest Array by Swapping Elements"),
    (2958, "Length of Longest Subarray With at Most K Frequency"),
    (2962, "Count Subarrays Where Max Element Appears at Least K Times"),
    (2965, "Find Missing and Repeated Values"),
    (2966, "Divide Array Into Arrays With Max Difference"),
    (2971, "Find Polygon with the Largest Perimeter"),
    (2976, "Minimum Cost to Convert String I"),
    (3011, "Find if Array Can Be Sorted"),
    (3016, "Minimum Number of Pushes to Type Word II"),
    (3042, "Count Prefix and Suffix Pairs I"),
    (3043, "Find the Length of the Longest Common Prefix"),
    (3045, "Count Prefix and Suffix Pairs II"),
    (3068, "Find the Maximum Sum of Node Values"),
    (3097, "Shortest Subarray With OR at Least K II"),
    (3105, "Longest Strictly Increasing or Strictly Decreasing Subarray"),
    (3108, "Minimum Cost Walk in Weighted Graph"),
    (3110, "Score of a String"),
    (3133, "Minimum Array End"),
    (3151, "Special Array I"),
    (3169, "Count Days Without Meetings"),
    (3174, "Clear Digits"),
    (3191, "Minimum Operations to Make Binary Array Elements Equal to One I"),
    (3199, "Count Triplets with Even XOR Set Bits I"),
    (3203, "Find Minimum Diameter After Merging Two Trees"),
    (3208, "Alternating Groups II"),
    (3217, "Delete Nodes From Linked List Present in Array"),
    (3223, "Minimum Length of String After Operations"),
    (3243, "Shortest Distance After Road Addition Queries I"),
    (3254, "Find the Power of K-Size Subarrays I"),
    (3264, "Final Array State After K Multiplication Operations I"),
    (3306, "Count of Substrings Containing Every Vowel and K Consonants II"),
    (3394, "Check if Grid can be Cut into Sections"),
    (3434, "Maximum Frequency After Subarray Operation"),
    (3442, "Maximum Difference Between Even and Odd Frequency I"),
    (3481, "Apply Substitutions"),
    (3572, "Maximize Y-Sum by Picking a Triplet of Distinct X-Values"),
    (3711, "Maximum Transactions Without Negative Balance"),
]
