import pytest

from leetcode_py import logged_test

from .helpers import assert_all_one, run_all_one
from .solution import AllOne


class TestAllOne:
    @logged_test
    @pytest.mark.parametrize(
        "operations, inputs, expected",
        [
            (
                [
                    "AllOne",
                    "inc",
                    "inc",
                    "get_max_key",
                    "get_min_key",
                    "inc",
                    "get_max_key",
                    "get_min_key",
                ],
                [[], ["hello"], ["hello"], [], [], ["leet"], [], []],
                [None, None, None, "hello", "hello", None, "hello", "leet"],
            ),
            (["AllOne", "get_max_key", "get_min_key"], [[], [], []], [None, "", ""]),
            (
                ["AllOne", "inc", "get_max_key", "get_min_key"],
                [[], ["a"], [], []],
                [None, None, "a", "a"],
            ),
            (
                ["AllOne", "inc", "inc", "get_max_key", "get_min_key"],
                [[], ["a"], ["a"], [], []],
                [None, None, None, "a", "a"],
            ),
            (
                ["AllOne", "inc", "inc", "inc", "get_max_key", "get_min_key"],
                [[], ["a"], ["b"], ["b"], [], []],
                [None, None, None, None, "b", "a"],
            ),
            (
                ["AllOne", "inc", "inc", "inc", "dec", "dec", "get_max_key", "get_min_key"],
                [[], ["a"], ["b"], ["b"], ["b"], ["b"], [], []],
                [None, None, None, None, None, None, "a", "a"],
            ),
            (
                ["AllOne", "inc", "inc", "dec", "dec", "get_max_key", "get_min_key"],
                [[], ["a"], ["b"], ["b"], ["a"], [], []],
                [None, None, None, None, None, "", ""],
            ),
            (
                ["AllOne", "inc", "inc", "inc", "inc", "inc", "inc", "get_max_key", "get_min_key"],
                [[], ["a"], ["b"], ["b"], ["c"], ["c"], ["c"], [], []],
                [None, None, None, None, None, None, None, "c", "a"],
            ),
            (
                ["AllOne", "inc", "dec", "inc", "get_max_key", "get_min_key"],
                [[], ["a"], ["a"], ["b"], [], []],
                [None, None, None, None, "b", "b"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "inc",
                    "inc",
                    "get_max_key",
                    "dec",
                    "dec",
                    "get_max_key",
                    "get_min_key",
                ],
                [[], ["a"], ["a"], ["b"], [], ["a"], ["a"], [], []],
                [None, None, None, None, "a", None, None, "b", "b"],
            ),
            (
                ["AllOne", "inc", "inc", "inc", "inc", "inc", "inc", "get_max_key", "get_min_key"],
                [[], ["a"], ["b"], ["c"], ["c"], ["b"], ["c"], [], []],
                [None, None, None, None, None, None, None, "c", "a"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "inc",
                    "inc",
                    "inc",
                    "dec",
                    "get_max_key",
                    "get_min_key",
                    "dec",
                    "get_max_key",
                    "get_min_key",
                ],
                [[], ["k"], ["k"], ["k"], ["k"], ["k"], [], [], ["k"], [], []],
                [None, None, None, None, None, None, "k", "k", None, "k", "k"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "inc",
                    "inc",
                    "inc",
                    "dec",
                    "get_max_key",
                    "dec",
                    "get_max_key",
                    "get_min_key",
                ],
                [[], ["a"], ["a"], ["b"], ["b"], ["b"], [], ["b"], [], []],
                [None, None, None, None, None, None, "a", None, "a", "a"],
            ),
            (
                ["AllOne", "inc", "inc", "inc", "get_max_key", "get_min_key"],
                [[], ["abcdefghij"], ["x"], ["abcdefghij"], [], []],
                [None, None, None, None, "abcdefghij", "x"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "inc",
                    "inc",
                    "get_max_key",
                    "get_min_key",
                    "dec",
                    "inc",
                    "get_max_key",
                    "get_min_key",
                ],
                [[], ["m"], ["n"], ["m"], [], [], ["m"], ["n"], [], []],
                [None, None, None, None, "m", "n", None, None, "n", "m"],
            ),
            (
                ["AllOne", "inc", "dec", "inc", "dec", "inc", "get_max_key", "get_min_key"],
                [[], ["p"], ["p"], ["p"], ["p"], ["p"], [], []],
                [None, None, None, None, None, None, "p", "p"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "get_max_key",
                    "inc",
                    "inc",
                    "inc",
                    "get_min_key",
                    "dec",
                    "inc",
                    "get_min_key",
                    "get_min_key",
                ],
                [[], ["b"], [], ["b"], ["c"], ["b"], [], ["c"], ["ab"], [], []],
                [None, None, "b", None, None, None, "c", None, None, "ab", "ab"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "dec",
                    "inc",
                    "dec",
                    "inc",
                    "get_min_key",
                    "get_min_key",
                    "inc",
                    "inc",
                    "inc",
                    "dec",
                    "dec",
                    "dec",
                ],
                [
                    [],
                    ["d"],
                    ["d"],
                    ["cd"],
                    ["cd"],
                    ["cd"],
                    [],
                    [],
                    ["ab"],
                    ["ab"],
                    ["a"],
                    ["ab"],
                    ["a"],
                    ["cd"],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "cd",
                    "cd",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                ],
            ),
            (
                ["AllOne", "inc", "inc", "inc", "get_min_key", "inc", "dec", "get_min_key"],
                [[], ["cd"], ["c"], ["c"], [], ["d"], ["d"], []],
                [None, None, None, None, "cd", None, None, "cd"],
            ),
            (
                [
                    "AllOne",
                    "inc",
                    "inc",
                    "dec",
                    "inc",
                    "inc",
                    "inc",
                    "inc",
                    "get_max_key",
                    "inc",
                    "inc",
                    "dec",
                    "dec",
                ],
                [
                    [],
                    ["a"],
                    ["d"],
                    ["a"],
                    ["a"],
                    ["a"],
                    ["a"],
                    ["cd"],
                    [],
                    ["ab"],
                    ["b"],
                    ["d"],
                    ["cd"],
                ],
                [None, None, None, None, None, None, None, None, "a", None, None, None, None],
            ),
        ],
    )
    def test_all_one(
        self, operations: list[str], inputs: list[list[str]], expected: list[str | None]
    ):
        result, _ = run_all_one(AllOne, operations, inputs)
        assert_all_one(result, expected)
