[settings]
pipx.uvx = true

[tools]
actionlint = "latest"
bun = "latest"
"npm:actions-up" = "latest"
"npm:mintlify" = "latest"
"pipx:bakefile" = {version = "latest", extras = "locked"}
"pipx:pre-commit" = "latest"
"pipx:toml-sort" = "latest"
"pipx:zerv-version" = "latest"
uv = "latest"
