import pytest

from leetcode_py import logged_test

from .helpers import assert_number_of_lines, run_number_of_lines
from .solution import Solution


class TestNumberOfLinesToWriteString:
    def setup_method(self):
        self.solution = Solution()

    @logged_test
    @pytest.mark.parametrize(
        "widths, s, expected",
        [
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "abcdefghijklmnopqrstuvwxyz",
                [3, 60],
            ),
            (
                [
                    4,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "bbbcccdddaaa",
                [2, 4],
            ),
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "a",
                [1, 10],
            ),
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "ab",
                [1, 20],
            ),
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "aaaaaaaaaa",
                [1, 100],
            ),
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "aaaaaaaaaaa",
                [2, 10],
            ),
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "aaaaaaaaaaaaaaaaaaaa",
                [2, 100],
            ),
            (
                [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                [1, 100],
            ),
            (
                [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                [2, 2],
            ),
            (
                [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                "abcdefghijklmnopqrstuvwxyz",
                [1, 52],
            ),
            (
                [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",
                [2, 4],
            ),
            (
                [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
                "bbbbbbbbbbbbbbbbbbbbb",
                [2, 5],
            ),
            (
                [
                    3,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                ],
                "abc",
                [1, 23],
            ),
            (
                [
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    2,
                ],
                "zzz",
                [1, 6],
            ),
            (
                [2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9],
                "abcdefghijklmnopqrstuvwxyz",
                [2, 54],
            ),
            (
                [9, 2, 6, 10, 7, 6, 5, 9, 3, 9, 9, 7, 8, 6, 5, 3, 10, 2, 5, 5, 3, 3, 2, 5, 8, 3],
                "bkdgddrqeivupfzceyhjzwmeelgkfirsgu",
                [2, 98],
            ),
            (
                [7, 6, 3, 3, 8, 4, 8, 9, 4, 6, 8, 6, 10, 8, 10, 8, 2, 8, 9, 5, 6, 10, 4, 4, 5, 10],
                "jphic",
                [1, 30],
            ),
            (
                [6, 10, 5, 6, 5, 7, 10, 6, 5, 3, 3, 3, 8, 7, 7, 3, 4, 3, 4, 7, 2, 5, 9, 8, 10, 6],
                "zcmgypktjwozv",
                [1, 82],
            ),
            (
                [2, 9, 4, 4, 8, 7, 6, 10, 5, 5, 3, 7, 5, 10, 8, 4, 9, 3, 4, 9, 2, 7, 5, 5, 8, 10],
                "gjqboj",
                [1, 42],
            ),
            (
                [6, 10, 9, 9, 2, 4, 9, 9, 9, 4, 2, 3, 8, 3, 7, 5, 8, 3, 4, 9, 10, 4, 7, 7, 2, 3],
                "aodexzgelclqmjjhbiwanzvn",
                [2, 45],
            ),
        ],
    )
    def test_number_of_lines(self, widths: list[int], s: str, expected: list[int]):
        result = run_number_of_lines(Solution, widths, s)
        assert_number_of_lines(result, expected)
