import pytest

from leetcode_py import logged_test

from .helpers import assert_binary_search_tree_iterator, run_binary_search_tree_iterator
from .solution import BSTIterator


class TestBinarySearchTreeIterator:
    @logged_test
    @pytest.mark.parametrize(
        "root_list, operations, expected",
        [
            (
                [7, 3, 15, None, None, 9, 20],
                [
                    "next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                ],
                [None, 3, 7, True, 9, True, 15, True, 20, False],
            ),
            ([5], ["next", "has_next"], [None, 5, False]),
            ([3, 1, None, 2], ["next", "next", "next", "has_next"], [None, 2, 1, 3, False]),
            ([1, None, 2, None, 3], ["next", "next", "next", "has_next"], [None, 1, 2, 3, False]),
            (
                [4, 2, 6, 1, 3, 5, 7],
                [
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                ],
                [None, 1, True, 2, True, 3, True, 4, True, 5, True, 6, True, 7, False],
            ),
            ([2, 1, 3], ["next", "next", "next", "has_next"], [None, 1, 2, 3, False]),
            ([1], ["has_next", "has_next", "next", "has_next"], [None, True, True, 1, False]),
            (
                [8, 4, 12, 2, 6, 10, 14, 1, 3, 5, 7, 9, 11, 13, 15],
                [
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                ],
                [
                    None,
                    True,
                    1,
                    True,
                    2,
                    True,
                    3,
                    True,
                    4,
                    True,
                    5,
                    True,
                    6,
                    True,
                    7,
                    True,
                    8,
                    True,
                    9,
                    True,
                    10,
                    True,
                    11,
                    True,
                    12,
                    True,
                    13,
                    True,
                    14,
                    True,
                    15,
                    False,
                ],
            ),
            ([2, 1], ["next", "has_next", "next", "has_next"], [None, 1, True, 2, False]),
            ([2, None, 3], ["next", "next", "has_next"], [None, 2, 3, False]),
            (
                [5, 4, None, 3, None, 2, None, 1],
                ["next", "next", "next", "next", "next", "has_next"],
                [None, 1, 2, 3, 4, 5, False],
            ),
            (
                [1000000, 0],
                ["next", "has_next", "next", "has_next"],
                [None, 0, True, 1000000, False],
            ),
            (
                [6, 3, 8, 1, 4, 7, 9],
                [
                    "has_next",
                    "next",
                    "next",
                    "has_next",
                    "next",
                    "next",
                    "has_next",
                    "next",
                    "next",
                    "has_next",
                    "next",
                    "has_next",
                ],
                [None, True, 1, 3, True, 4, 6, True, 7, 8, True, 9, False],
            ),
            (
                [3, 1, 4],
                ["next", "next", "next", "has_next", "has_next"],
                [None, 1, 3, 4, False, False],
            ),
            (
                [10, 5, 15, None, None, 12, 20],
                ["next", "next", "next", "next", "next", "has_next"],
                [None, 5, 10, 12, 15, 20, False],
            ),
        ],
    )
    def test_binary_search_tree_iterator(
        self, root_list: list[int | None], operations: list[str], expected: list[int | bool | None]
    ):
        result, _ = run_binary_search_tree_iterator(BSTIterator, root_list, operations)
        assert_binary_search_tree_iterator(result, expected)
