import pytest

from leetcode_py import logged_test

from .helpers import assert_missing_number, run_missing_number
from .solution import Solution


class TestTestMissingNumber:
    def setup_method(self):
        self.solution = Solution()

    @logged_test
    @pytest.mark.parametrize(
        "solution_class, nums, expected",
        [
            (Solution, [3, 0, 1], 2),
            (Solution, [0, 1], 2),
            (Solution, [9, 6, 4, 2, 3, 5, 7, 0, 1], 8),
            (Solution, [0], 1),
            (Solution, [1], 0),
            (Solution, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 10),
            (Solution, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 0),
            (Solution, [0, 1, 2, 3, 4, 6, 7, 8, 9, 10], 5),
            (Solution, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 0),
            (Solution, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 20),
            (Solution, [2, 0, 1], 3),
            (Solution, [1, 0], 2),
            (
                Solution,
                [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99,
                    100,
                ],
                101,
            ),
        ],
    )
    def test_missing_number(self, solution_class, nums: list[int], expected: int):
        result = run_missing_number(solution_class, nums)
        assert_missing_number(result, expected)
