import pytest

from leetcode_py import logged_test

from .helpers import assert_underground_system_operations, run_underground_system_operations
from .solution import UndergroundSystem


class TestDesignUndergroundSystem:
    @logged_test
    @pytest.mark.parametrize(
        "operations, inputs, expected",
        [
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "check_in",
                    "get_average_time",
                    "check_out",
                    "get_average_time",
                ],
                [
                    [],
                    [45, "Leyton", 3],
                    [32, "Paradise", 8],
                    [27, "Leyton", 10],
                    [45, "Waterloo", 15],
                    [27, "Waterloo", 20],
                    [32, "Cambridge", 22],
                    ["Paradise", "Cambridge"],
                    ["Leyton", "Waterloo"],
                    [10, "Leyton", 24],
                    ["Leyton", "Waterloo"],
                    [10, "Waterloo", 38],
                    ["Leyton", "Waterloo"],
                ],
                [None, None, None, None, None, None, None, 14.0, 11.0, None, 11.0, None, 12.0],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_out",
                    "get_average_time",
                    "check_in",
                    "check_out",
                    "get_average_time",
                    "check_in",
                    "check_out",
                    "get_average_time",
                ],
                [
                    [],
                    [10, "Leyton", 3],
                    [10, "Paradise", 8],
                    ["Leyton", "Paradise"],
                    [5, "Leyton", 10],
                    [5, "Paradise", 16],
                    ["Leyton", "Paradise"],
                    [2, "Leyton", 21],
                    [2, "Paradise", 30],
                    ["Leyton", "Paradise"],
                ],
                [None, None, None, 5.0, None, None, 5.5, None, None, 6.666666666666667],
            ),
            (
                ["UndergroundSystem", "check_in", "check_out", "get_average_time"],
                [[], [1, "A", 5], [1, "B", 12], ["A", "B"]],
                [None, None, None, 7.0],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_out",
                    "get_average_time",
                    "check_in",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [7, "Alpha", 1],
                    [7, "Beta", 9],
                    ["Alpha", "Beta"],
                    [8, "Beta", 20],
                    [8, "Alpha", 25],
                    ["Beta", "Alpha"],
                    ["Alpha", "Beta"],
                ],
                [None, None, None, 8.0, None, None, 5.0, 8.0],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [100, "King", 2],
                    [101, "King", 4],
                    [102, "Cross", 6],
                    [100, "Park", 22],
                    [102, "Queen", 30],
                    [101, "Park", 34],
                    ["King", "Park"],
                    ["Cross", "Queen"],
                ],
                [None, None, None, None, None, None, None, 25.0, 24.0],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_out",
                    "check_in",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [3, "North", 10],
                    [3, "South", 40],
                    [3, "East", 50],
                    [3, "West", 65],
                    ["North", "South"],
                    ["East", "West"],
                ],
                [None, None, None, None, None, 30.0, 15.0],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                ],
                [[], [9, "One", 100], [9, "Two", 110], ["One", "Two"], ["One", "Two"]],
                [None, None, None, 10.0, 10.0],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "check_in",
                    "check_out",
                    "get_average_time",
                ],
                [
                    [],
                    [11, "S1", 1],
                    [12, "S1", 2],
                    [11, "S2", 21],
                    [12, "S2", 22],
                    ["S1", "S2"],
                    [13, "S1", 30],
                    [13, "S2", 45],
                    ["S1", "S2"],
                ],
                [None, None, None, None, None, 20.0, None, None, 18.333333333333332],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [1, "St3", 12],
                    [2, "St3", 17],
                    [3, "St1", 21],
                    [1, "St1", 23],
                    [2, "St2", 24],
                    [3, "St0", 26],
                    ["St3", "St1"],
                    ["St3", "St2"],
                    ["St1", "St0"],
                    [4, "St0", 31],
                    [5, "St3", 36],
                    [6, "St1", 40],
                    [4, "St1", 45],
                    [5, "St0", 47],
                    [6, "St2", 51],
                    ["St3", "St1"],
                    ["St3", "St2"],
                    ["St1", "St0"],
                    ["St0", "St1"],
                    ["St3", "St0"],
                    ["St1", "St2"],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    11.0,
                    7.0,
                    5.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    11.0,
                    7.0,
                    5.0,
                    14.0,
                    11.0,
                    11.0,
                ],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [1, "St3", 13],
                    [2, "St2", 16],
                    [3, "St3", 18],
                    [1, "St2", 19],
                    [2, "St3", 23],
                    [3, "St1", 28],
                    ["St3", "St2"],
                    ["St2", "St3"],
                    ["St3", "St1"],
                    [4, "St0", 33],
                    [5, "St1", 38],
                    [6, "St2", 42],
                    [4, "St2", 44],
                    [5, "St0", 46],
                    [6, "St1", 51],
                    ["St3", "St2"],
                    ["St2", "St3"],
                    ["St3", "St1"],
                    ["St0", "St2"],
                    ["St1", "St0"],
                    ["St2", "St1"],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    6.0,
                    7.0,
                    10.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    6.0,
                    7.0,
                    10.0,
                    11.0,
                    8.0,
                    9.0,
                ],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [1, "St2", 14],
                    [2, "St1", 17],
                    [3, "St1", 19],
                    [1, "St1", 21],
                    [2, "St0", 23],
                    [3, "St2", 28],
                    ["St2", "St1"],
                    ["St1", "St0"],
                    ["St1", "St2"],
                    [4, "St3", 29],
                    [5, "St0", 31],
                    [6, "St1", 34],
                    [4, "St2", 35],
                    [5, "St3", 39],
                    [6, "St2", 41],
                    ["St2", "St1"],
                    ["St1", "St0"],
                    ["St1", "St2"],
                    ["St3", "St2"],
                    ["St0", "St3"],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    7.0,
                    6.0,
                    9.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    7.0,
                    6.0,
                    8.0,
                    6.0,
                    8.0,
                ],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [1, "St0", 15],
                    [2, "St1", 20],
                    [3, "St2", 23],
                    [1, "St3", 26],
                    [2, "St3", 29],
                    [3, "St3", 33],
                    ["St0", "St3"],
                    ["St1", "St3"],
                    ["St2", "St3"],
                    [4, "St2", 34],
                    [5, "St2", 36],
                    [6, "St2", 39],
                    [4, "St1", 42],
                    [5, "St1", 44],
                    [6, "St0", 45],
                    ["St0", "St3"],
                    ["St1", "St3"],
                    ["St2", "St3"],
                    ["St2", "St1"],
                    ["St2", "St0"],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    11.0,
                    9.0,
                    10.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    11.0,
                    9.0,
                    10.0,
                    8.0,
                    6.0,
                ],
            ),
            (
                [
                    "UndergroundSystem",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "check_in",
                    "check_in",
                    "check_in",
                    "check_out",
                    "check_out",
                    "check_out",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                    "get_average_time",
                ],
                [
                    [],
                    [1, "St1", 16],
                    [2, "St0", 17],
                    [3, "St1", 19],
                    [1, "St0", 20],
                    [2, "St2", 22],
                    [3, "St0", 24],
                    ["St1", "St0"],
                    ["St0", "St2"],
                    [4, "St3", 27],
                    [5, "St2", 30],
                    [6, "St2", 34],
                    [4, "St1", 37],
                    [5, "St1", 39],
                    [6, "St3", 42],
                    ["St1", "St0"],
                    ["St0", "St2"],
                    ["St3", "St1"],
                    ["St2", "St1"],
                    ["St2", "St3"],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    4.5,
                    5.0,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    4.5,
                    5.0,
                    10.0,
                    9.0,
                    8.0,
                ],
            ),
        ],
    )
    def test_underground_system(
        self, operations: list[str], inputs: list[list], expected: list[float | None]
    ):
        result, _ = run_underground_system_operations(UndergroundSystem, operations, inputs)
        assert_underground_system_operations(result, expected)
