import pytest

from leetcode_py import logged_test

from .helpers import assert_diameter, run_diameter
from .solution import Solution


class TestDiameterOfNAryTree:
    def setup_method(self):
        self.solution = Solution()

    @logged_test
    @pytest.mark.parametrize(
        "root_list, expected",
        [
            ([1, None, 3, 2, 4, None, 5, 6], 3),
            ([1, None, 2, None, 3, 4, None, 5, None, 6], 4),
            (
                [
                    1,
                    None,
                    2,
                    3,
                    4,
                    5,
                    None,
                    None,
                    6,
                    7,
                    None,
                    8,
                    None,
                    9,
                    10,
                    None,
                    None,
                    11,
                    None,
                    12,
                    None,
                    13,
                    None,
                    None,
                    14,
                ],
                7,
            ),
            ([1], 0),
            ([1, None, 2], 1),
            ([1, None, 2, 3], 2),
            ([1, None, 2, 3, 4], 2),
            ([1, None, 2, None, 3], 2),
            ([1, None, 2, None, 3, None, 4], 3),
            ([1, None, 2, None, 3, 4], 2),
            ([1, None, 2, 3, None, 4, 5], 3),
            ([1, None, 2, 3, 4, 5, None, 6], 3),
            ([1, None, 2, 3, None, 4, None, None, 5], 4),
            ([1, None, 2, 4, 5, 6, None, 3, None, None, 7], 4),
            ([1, None, 2, 3, 4, 8, None, None, None, 5, None, 9, None, 6, 7], 5),
            (
                [
                    1,
                    None,
                    2,
                    7,
                    8,
                    None,
                    3,
                    None,
                    12,
                    None,
                    None,
                    4,
                    6,
                    None,
                    None,
                    5,
                    None,
                    9,
                    None,
                    10,
                    None,
                    None,
                    11,
                ],
                8,
            ),
            (
                [
                    1,
                    None,
                    2,
                    5,
                    7,
                    None,
                    3,
                    6,
                    None,
                    10,
                    None,
                    13,
                    None,
                    4,
                    8,
                    None,
                    9,
                    None,
                    None,
                    None,
                    None,
                    11,
                    None,
                    15,
                    None,
                    12,
                    14,
                ],
                7,
            ),
            (
                [
                    1,
                    None,
                    2,
                    3,
                    4,
                    5,
                    7,
                    10,
                    None,
                    None,
                    11,
                    12,
                    15,
                    None,
                    None,
                    6,
                    9,
                    14,
                    17,
                    None,
                    None,
                    None,
                    18,
                    None,
                    None,
                    16,
                    19,
                    20,
                    None,
                    8,
                    None,
                    13,
                ],
                6,
            ),
        ],
    )
    def test_diameter(self, root_list: list[int | None], expected: int):
        result = run_diameter(Solution, root_list)
        assert_diameter(result, expected)
