import pytest

from leetcode_py import logged_test

from .helpers import assert_flatten, run_flatten
from .solution import Solution


class TestFlattenAMultilevelDoublyLinkedList:
    def setup_method(self):
        self.solution = Solution()

    @logged_test
    @pytest.mark.parametrize(
        "head_list, expected_list",
        [
            ([], []),
            ([1], [1]),
            (
                [1, 2, 3, 4, 5, 6, None, None, None, 7, 8, 9, 10, None, None, 11, 12],
                [1, 2, 3, 7, 8, 11, 12, 9, 10, 4, 5, 6],
            ),
            ([1, 2, None, 3], [1, 3, 2]),
            ([5, None, 4], [5, 4]),
            ([1, None, 2], [1, 2]),
            ([2, 1, None, 3], [2, 3, 1]),
            ([1, 2, 3, None, 4, None, None, 5], [1, 4, 2, 5, 3]),
            ([1, 2, None, 3, 4, None, None, 5, 6, None, None, None, 7], [1, 3, 4, 5, 6, 2, 7]),
            ([1, None, 2, None, 3, None, 4], [1, 2, 3, 4]),
            (
                [9, 8, 7, 6, None, None, None, None, 5, 4, 3, None, None, None, 2, 1],
                [9, 8, 7, 6, 5, 4, 3, 2, 1],
            ),
            (
                [10, 20, 30, 40, None, 11, None, None, None, 31, 32, None, 41],
                [10, 11, 20, 30, 31, 41, 32, 40],
            ),
            (
                [5, 1, 5, None, None, 27, 23, None, 54, 45, None, None, None, 48, 54],
                [5, 1, 27, 54, 45, 23, 48, 54, 5],
            ),
            (
                [
                    7,
                    6,
                    6,
                    None,
                    27,
                    26,
                    35,
                    None,
                    None,
                    41,
                    51,
                    None,
                    None,
                    None,
                    None,
                    30,
                    33,
                    39,
                    None,
                    None,
                    41,
                    49,
                    None,
                    None,
                    None,
                    None,
                    30,
                    33,
                    39,
                    None,
                    None,
                    41,
                    49,
                ],
                [7, 27, 26, 41, 51, 35, 6, 30, 33, 41, 49, 39, 6, 30, 33, 41, 49, 39],
            ),
            (
                [
                    20,
                    14,
                    3,
                    6,
                    None,
                    22,
                    27,
                    22,
                    None,
                    57,
                    50,
                    None,
                    None,
                    None,
                    48,
                    None,
                    None,
                    57,
                    50,
                    None,
                    None,
                    None,
                    40,
                    33,
                    32,
                    None,
                    50,
                    None,
                    None,
                    60,
                    None,
                    None,
                    None,
                    26,
                    24,
                    37,
                    None,
                    None,
                    None,
                    None,
                    26,
                    35,
                    None,
                    None,
                    50,
                ],
                [
                    20,
                    22,
                    57,
                    50,
                    27,
                    48,
                    22,
                    57,
                    50,
                    14,
                    40,
                    50,
                    33,
                    60,
                    32,
                    3,
                    26,
                    24,
                    37,
                    6,
                    26,
                    35,
                    50,
                ],
            ),
            (
                [
                    10,
                    8,
                    None,
                    24,
                    33,
                    33,
                    None,
                    None,
                    50,
                    None,
                    None,
                    50,
                    None,
                    None,
                    26,
                    26,
                    26,
                    None,
                    60,
                    46,
                    None,
                    None,
                    None,
                    60,
                    46,
                    None,
                    None,
                    None,
                    60,
                    46,
                ],
                [10, 24, 33, 50, 33, 50, 8, 26, 60, 46, 26, 60, 46, 26, 60, 46],
            ),
            ([4, None, 31], [4, 31]),
            ([3], [3]),
            ([4, 16, None, 23, None, 45], [4, 23, 45, 16]),
            ([5, 8, 5, 20, None, None, None, None, 24, 26], [5, 8, 5, 20, 24, 26]),
        ],
    )
    def test_flatten(self, head_list: list[int | None], expected_list: list[int | None]):
        result = run_flatten(Solution, head_list)
        assert_flatten(result, expected_list)
