import pytest

from leetcode_py import logged_test

from .helpers import assert_leaderboard, run_leaderboard
from .solution import Leaderboard


class TestDesignALeaderboard:
    @logged_test
    @pytest.mark.parametrize(
        "operations, inputs, expected",
        [
            (
                [
                    "Leaderboard",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "top",
                    "reset",
                    "reset",
                    "add_score",
                    "top",
                ],
                [[], [1, 73], [2, 56], [3, 39], [4, 51], [5, 4], [1], [1], [2], [2, 51], [3]],
                [None, None, None, None, None, None, 73, None, None, None, 141],
            ),
            (["Leaderboard", "add_score", "top"], [[], [1, 10], [1]], [None, None, 10]),
            (
                ["Leaderboard", "add_score", "add_score", "add_score", "top"],
                [[], [1, 50], [2, 50], [3, 50], [2]],
                [None, None, None, None, 100],
            ),
            (
                ["Leaderboard", "add_score", "add_score", "top"],
                [[], [1, 10], [1, 10], [1]],
                [None, None, None, 20],
            ),
            (
                ["Leaderboard", "add_score", "reset", "add_score", "top"],
                [[], [1, 50], [1], [1, 5], [1]],
                [None, None, None, None, 5],
            ),
            (
                ["Leaderboard", "add_score", "add_score", "add_score", "top"],
                [[], [1, 1], [2, 2], [3, 3], [3]],
                [None, None, None, None, 6],
            ),
            (
                ["Leaderboard", "add_score", "add_score", "reset", "top"],
                [[], [1, 30], [2, 20], [1], [1]],
                [None, None, None, None, 20],
            ),
            (
                [
                    "Leaderboard",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "reset",
                    "reset",
                    "top",
                ],
                [[], [1, 10], [2, 20], [3, 30], [4, 40], [1], [2], [2]],
                [None, None, None, None, None, None, None, 70],
            ),
            (
                ["Leaderboard", "add_score", "add_score", "top", "top"],
                [[], [1, 100], [2, 1], [2], [1]],
                [None, None, None, 101, 100],
            ),
            (
                ["Leaderboard", "add_score", "add_score", "top", "reset", "add_score", "top"],
                [[], [1, 5], [2, 6], [2], [1], [1, 7], [2]],
                [None, None, None, 11, None, None, 13],
            ),
            (
                ["Leaderboard", "add_score", "top", "add_score", "top", "top"],
                [[], [1, 7], [1], [2, 9], [2], [1]],
                [None, None, 7, None, 16, 9],
            ),
            (
                ["Leaderboard", "add_score", "add_score", "reset", "reset", "add_score", "top"],
                [[], [1, 99], [2, 99], [1], [2], [3, 4], [1]],
                [None, None, None, None, None, None, 4],
            ),
            (
                [
                    "Leaderboard",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "top",
                    "add_score",
                    "top",
                    "reset",
                    "top",
                ],
                [[], [1, 3], [2, 6], [3, 9], [4, 12], [3], [2, 1], [3], [1], [3]],
                [None, None, None, None, None, 27, None, 28, None, 28],
            ),
            (
                [
                    "Leaderboard",
                    "add_score",
                    "add_score",
                    "add_score",
                    "reset",
                    "add_score",
                    "add_score",
                    "add_score",
                    "top",
                    "reset",
                    "top",
                ],
                [[], [1, 10], [2, 20], [3, 30], [2], [2, 5], [4, 40], [2, 15], [3], [3], [3]],
                [None, None, None, None, None, None, None, None, 90, None, 70],
            ),
            (
                [
                    "Leaderboard",
                    "add_score",
                    "reset",
                    "add_score",
                    "add_score",
                    "reset",
                    "add_score",
                    "add_score",
                    "reset",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "top",
                    "reset",
                    "add_score",
                    "reset",
                    "add_score",
                    "add_score",
                    "top",
                    "top",
                    "reset",
                    "reset",
                    "top",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "add_score",
                    "top",
                    "top",
                    "add_score",
                    "add_score",
                    "reset",
                    "add_score",
                    "top",
                    "add_score",
                    "top",
                ],
                [
                    [],
                    [5, 16],
                    [5],
                    [3, 83],
                    [3, 46],
                    [3],
                    [5, 90],
                    [1, 84],
                    [1],
                    [5, 53],
                    [5, 38],
                    [4, 67],
                    [6, 69],
                    [4, 38],
                    [1],
                    [4],
                    [5, 6],
                    [6],
                    [1, 37],
                    [6, 54],
                    [3],
                    [3],
                    [1],
                    [6],
                    [1],
                    [5, 34],
                    [5, 24],
                    [4, 20],
                    [4, 31],
                    [5, 99],
                    [3, 71],
                    [2, 39],
                    [1],
                    [2],
                    [2, 82],
                    [2, 54],
                    [2],
                    [2, 12],
                    [3],
                    [6, 18],
                    [5],
                ],
                [
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    181,
                    None,
                    None,
                    None,
                    None,
                    None,
                    278,
                    278,
                    None,
                    None,
                    187,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    344,
                    415,
                    None,
                    None,
                    None,
                    None,
                    466,
                    None,
                    496,
                ],
            ),
        ],
    )
    def test_leaderboard(
        self, operations: list[str], inputs: list[list[int]], expected: list[int | None]
    ):
        result, _ = run_leaderboard(Leaderboard, operations, inputs)
        assert_leaderboard(result, expected)
