#!/usr/bin/env python3
"""Generate docs/catalog/ pages from the JSON problem templates.

Output is deterministic: same tags.json5 + problems/*.json in, same mdx out.
Run with --check to verify committed pages are up to date without writing.
"""

import argparse
import json
import re
import sys
from pathlib import Path

import json5

REPO_ROOT = Path(__file__).resolve().parent.parent
TAGS_FILE = REPO_ROOT / "src/leetcode_py/cli/resources/leetcode/json/tags.json5"
PROBLEMS_DIR = REPO_ROOT / "src/leetcode_py/cli/resources/leetcode/json/problems"
CATALOG_DIR = REPO_ROOT / "docs/catalog"

GENERATED_HEADER = "{/* GENERATED by scripts/gen_catalog.py - do not edit */}"
GITHUB_BASE = "https://github.com/wislertt/leetcode-py/blob/main/leetcode"

# Display name and SEO title per collection tag. Order follows tags.json5.
# Origin links live on the hand-written Collections page, not here.
# SEO titles are query-shaped, unique, and <= 46 chars: Mintlify appends
# " - leetcode-py" (14 chars), landing rendered titles at 50-60 chars.
# sidebarTitle carries the short label the nav shows.
COLLECTION_META: dict[str, dict[str, str]] = {
    "grind-75": {
        "label": "Grind 75",
        "title": "Grind 75 in Python with Tested Solutions",
    },
    "grind": {
        "label": "Grind",
        "title": "Grind Collection in Python: Tested Solutions",
    },
    "blind-75": {
        "label": "Blind 75",
        "title": "Blind 75 in Python with Tested Solutions",
    },
    "neetcode-150": {
        "label": "NeetCode 150",
        "title": "NeetCode 150 in Python with Tested Solutions",
    },
    "neetcode-250": {
        "label": "NeetCode 250",
        "title": "NeetCode 250 in Python with Tested Solutions",
    },
    "neetcode": {
        "label": "NeetCode All",
        "title": "NeetCode All in Python with Tested Solutions",
    },
    "algo-master-75": {
        "label": "AlgoMaster 75",
        "title": "AlgoMaster 75 in Python with Tested Solutions",
    },
}

INDEX_PAGE_TITLE = "LeetCode Problem Catalog: All Collections"
ALL_PAGE_TITLE = "All LeetCode Problems in Python with Tests"

# Two-sentence keyword intro per collection: what the list is, that every
# problem generates a tested Python environment. The lcpy gen command line
# follows immediately after in the page body.
COLLECTION_INTRO: dict[str, str] = {
    "grind-75": (
        "Grind 75 is the essential-75 list from Tech Interview Handbook, "
        "ordered by a week-by-week study plan built around pattern coverage "
        "and time budget. Every problem generates a Python practice "
        "environment with a parametrized pytest suite and a tested reference "
        "solution."
    ),
    "grind": (
        "The extended Grind collection is a superset of Grind 75 for longer "
        "prep timelines, with broader coverage of the same interview "
        "patterns. Every problem generates a Python practice environment "
        "with a parametrized pytest suite and a tested reference solution."
    ),
    "blind-75": (
        "Blind 75 is the classic curated list that started pattern-based "
        "prep, covering everything from arrays and hashing to dynamic "
        "programming. Every problem generates a Python practice environment "
        "with a parametrized pytest suite and a tested reference solution."
    ),
    "neetcode-150": (
        "NeetCode 150 is a topic-by-topic roadmap from arrays and hashing "
        "through advanced graphs, built to pair with the NeetCode video "
        "explanations. Every problem generates a Python practice environment "
        "with a parametrized pytest suite and a tested reference solution."
    ),
    "neetcode-250": (
        "NeetCode 250 is the full NeetCode roadmap, the broadest list in "
        "this catalog, and coverage here is still growing. Every problem "
        "below generates a Python practice environment with a parametrized "
        "pytest suite and a tested reference solution."
    ),
    "neetcode": (
        "Every NeetCode problem in this catalog: all of NeetCode 150 plus "
        "everything added so far from the full roadmap. Generate all of it "
        "as tested Python practice environments with one command."
    ),
    "algo-master-75": (
        "AlgoMaster 75 is this repository's own curated 75, built for "
        "algorithmic mastery across the core interview patterns. Every "
        "problem generates a Python practice environment with a "
        "parametrized pytest suite and a tested reference solution."
    ),
}

DIFFICULTIES = ["Easy", "Medium", "Hard"]

# Difficulty pages split their rows into sequential chunks of at most this
# many rows, so no catalog page renders more than a screenful-of-screens
# worth of table (1164 rows on one page made the DOM enormous).
CHUNK_SIZE = 200

# SEO title per difficulty: part 1 gets the full query-shaped title, later
# parts append ", Part N" (Mintlify appends " - leetcode-py" on top).
DIFFICULTY_TITLES = {
    "Easy": "Easy LeetCode Problems in Python with Tests",
    "Medium": "Medium LeetCode Problems in Python with Tests",
    "Hard": "Hard LeetCode Problems in Python with Tests",
}

# Hand-written files whose problem count is injected between markers so the
# number never goes stale. README.md is plain markdown (HTML comment); .mdx
# files need JSX comments since MDX does not support HTML comments.
COUNT_FILES: dict[str, tuple[str, str]] = {
    "README.md": ("<!-- problem-count:start -->", "<!-- problem-count:end -->"),
    "docs/index.mdx": ("{/* problem-count:start */}", "{/* problem-count:end */}"),
    "docs/getting-started/why-leetcode-py.mdx": (
        "{/* problem-count:start */}",
        "{/* problem-count:end */}",
    ),
}


def load_tags() -> dict[str, list]:
    with open(TAGS_FILE) as f:
        return json5.load(f)


def load_problems() -> dict[str, dict]:
    problems: dict[str, dict] = {}
    for json_file in sorted(PROBLEMS_DIR.glob("*.json")):
        with open(json_file) as f:
            data = json.load(f)
        problems[data["problem_name"]] = {
            "number": int(data["problem_number"]),
            "title": data["problem_title"],
            "difficulty": data["difficulty"],
        }
    return problems


def resolve_tag(tags: dict[str, list], tag: str) -> list[str]:
    """Expand a tag list, following {"tag": ...} includes, dedup in order."""
    problems: list[str] = []
    for item in tags[tag]:
        if isinstance(item, dict):
            for name in resolve_tag(tags, item["tag"]):
                if name not in problems:
                    problems.append(name)
        elif item not in problems:
            problems.append(item)
    return problems


def tag_includes(tags: dict[str, list], tag: str) -> list[str]:
    return [item["tag"] for item in tags[tag] if isinstance(item, dict) and "tag" in item]


def difficulty_split(names: list[str], problems: dict[str, dict]) -> dict[str, int]:
    split = dict.fromkeys(DIFFICULTIES, 0)
    for name in names:
        split[problems[name]["difficulty"]] += 1
    return split


def problem_url(name: str) -> str:
    return f"/problems/{name.replace('_', '-')}"


def solution_url(name: str) -> str:
    return f"{GITHUB_BASE}/{name}/solution.py"


def split_phrase(split: dict[str, int]) -> str:
    return ", ".join(f"{split[d]} {d}" for d in DIFFICULTIES if split[d])


def chunked(names: list[str]) -> list[list[str]]:
    """Split into sequential chunks of at most CHUNK_SIZE rows."""
    return [names[i : i + CHUNK_SIZE] for i in range(0, len(names), CHUNK_SIZE)] or [[]]


def table_div(header: list[str], rows: list[str]) -> list[str]:
    """Markdown table wrapped in a div so custom.css can control column widths."""
    lines = [
        "",
        '<div className="sd-catalog-table">',
        "",
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
        *rows,
        "",
        "</div>",
        "",
    ]
    return lines


def render_collection_page(
    tag: str,
    names: list[str],
    problems: dict[str, dict],
    tags: dict[str, list],
) -> dict[Path, str]:
    """Collection pages, paginated in CHUNK_SIZE chunks like the difficulty pages."""
    display = COLLECTION_META[tag]["label"]
    title = COLLECTION_META[tag]["title"]
    split = difficulty_split(names, problems)
    includes = tag_includes(tags, tag)
    rows = sorted(names, key=lambda n: problems[n]["number"])
    parts = chunked(rows)

    include_line = ""
    if includes:
        refs = [f"[{COLLECTION_META[ref]['label']}](/catalog/{ref})" for ref in includes]
        include_line = f"\nThis collection includes every problem in {', '.join(refs)}.\n"

    pages: dict[Path, str] = {}
    for i, chunk in enumerate(parts, start=1):
        start = sum(len(c) for c in parts[: i - 1]) + 1
        end = start + len(chunk) - 1
        page_title = title if i == 1 else f"{display} in Python, Part {i}"
        description = (
            f"All {len(names)} problems in the {display} list: each generates a "
            "tested Python practice environment with a pytest suite and reference solutions."
        )
        if len(parts) > 1:
            description += f" Part {i} of {len(parts)}: problems {start}-{end}."
        slug = tag if i == 1 else f"{tag}-{i}"

        lines = [
            "---",
            f'title: "{page_title}"',
            f"sidebarTitle: {display if i == 1 else f'{display} ({start}-{end})'}",
            f'description: "{description}"',
            "---",
            "",
            GENERATED_HEADER,
            "",
            f"{display} holds {len(names)} problems ({split_phrase(split)}).",
            COLLECTION_INTRO[tag],
            include_line,
            "Generate the whole collection into the current directory:",
            "",
            "```bash",
            f"lcpy gen -t {tag}",
            "```",
            "",
        ]
        table_rows = [
            f"| {problems[name]['number']} | [{problems[name]['title']}]({problem_url(name)}) "
            f"| {problems[name]['difficulty']} | [solution.py]({solution_url(name)}) |"
            for name in chunk
        ]
        lines += table_div(["#", "Problem", "Difficulty", "Solution"], table_rows)
        if len(parts) > 1:
            lines += pagination_lines(tag, len(parts), i)
        pages[CATALOG_DIR / f"{slug}.mdx"] = "\n".join(lines)
    return pages


def difficulty_slug(difficulty: str, part: int) -> str:
    return difficulty.lower() if part == 1 else f"{difficulty.lower()}-{part}"


def pagination_lines(base: str, part_count: int, current: int) -> list[str]:
    links = [
        f"[{j}](/catalog/{difficulty_slug(base, j)})" if j != current else str(j)
        for j in range(1, part_count + 1)
    ]
    return ["", "Pages: " + ", ".join(links), ""]


def render_all_pages(problems: dict[str, dict]) -> dict[Path, str]:
    """All-problems pages: the full list, paginated like the difficulty pages."""
    split = difficulty_split(list(problems), problems)
    parts = chunked(sorted(problems, key=lambda n: problems[n]["number"]))
    intro_links = ", ".join(
        f"[{difficulty}](/catalog/{difficulty_slug(difficulty, 1)})" for difficulty in DIFFICULTIES
    )
    pages: dict[Path, str] = {}
    for i, chunk in enumerate(parts, start=1):
        start = sum(len(c) for c in parts[: i - 1]) + 1
        end = start + len(chunk) - 1
        title = ALL_PAGE_TITLE if i == 1 else "All LeetCode Problems in Python, Part " + str(i)
        description = (
            "Every LeetCode problem in the catalog with difficulty, collections, "
            f"and tested Python solutions. Part {i} of {len(parts)}: problems "
            f"{start}-{end}."
        )
        lines = [
            "---",
            f'title: "{title}"',
            f"sidebarTitle: {'All Problems' if i == 1 else f'All ({start}-{end})'}",
            f'description: "{description}"',
            "---",
            "",
            GENERATED_HEADER,
            "",
            f"Every problem shipped in this repository: {len(problems)} problems "
            f"({split_phrase(split)}).",
        ]
        if i == 1:
            lines += [
                "",
                "Generate every problem directory into the current directory:",
                "",
                "```bash",
                "lcpy gen --all",
                "```",
                "",
                f"Browse by difficulty: {intro_links}.",
            ]
        table_rows = [
            f"| {problems[name]['number']} | [{problems[name]['title']}]({problem_url(name)}) "
            f"| {problems[name]['difficulty']} | [solution.py]({solution_url(name)}) |"
            for name in chunk
        ]
        lines += ["", *table_div(["#", "Problem", "Difficulty", "Solution"], table_rows)]
        lines += pagination_lines("All", len(parts), i)
        pages[CATALOG_DIR / f"{difficulty_slug('All', i)}.mdx"] = "\n".join(lines)
    return pages


def render_difficulty_pages(problems: dict[str, dict]) -> dict[Path, str]:
    pages: dict[Path, str] = {}
    for difficulty in DIFFICULTIES:
        rows = sorted(
            (n for n in problems if problems[n]["difficulty"] == difficulty),
            key=lambda n: problems[n]["number"],
        )
        parts = chunked(rows)
        for i, chunk in enumerate(parts, start=1):
            slug = difficulty_slug(difficulty, i)
            title = (
                DIFFICULTY_TITLES[difficulty]
                if i == 1
                else f"{difficulty} LeetCode Problems in Python, Part {i}"
            )
            start = sum(len(c) for c in parts[: i - 1]) + 1
            end = start + len(chunk) - 1
            description = (
                f"All {len(rows)} {difficulty} LeetCode problems with tested Python "
                f"solutions. Part {i} of {len(parts)}: problems {start}-{end}."
            )
            lines = [
                "---",
                f'title: "{title}"',
                f"sidebarTitle: {difficulty if i == 1 else f'{difficulty} ({start}-{end})'}",
                f'description: "{description}"',
                "---",
                "",
                GENERATED_HEADER,
                "",
                f"{difficulty} holds {len(rows)} problems.",
            ]

            table_rows = [
                f"| {problems[name]['number']} | [{problems[name]['title']}]({problem_url(name)}) "
                f"| {difficulty} | [solution.py]({solution_url(name)}) |"
                for name in chunk
            ]
            lines += table_div(["#", "Problem", "Difficulty", "Solution"], table_rows)
            lines += pagination_lines(difficulty, len(parts), i)
            pages[CATALOG_DIR / f"{slug}.mdx"] = "\n".join(lines)
    return pages


def render_index_page(
    collections: dict[str, list[str]],
    problems: dict[str, dict],
) -> str:
    total_split = difficulty_split(list(problems), problems)
    intro_links = ", ".join(
        f"[{difficulty}](/catalog/{difficulty_slug(difficulty, 1)})" for difficulty in DIFFICULTIES
    )

    lines = [
        "---",
        f'title: "{INDEX_PAGE_TITLE}"',
        "sidebarTitle: Catalog",
        'description: "Every problem in every collection, generated from the '
        'JSON templates so counts never go stale."',
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"All {len(problems)} problems across {len(collections)} collections, "
        "generated straight from the templates so counts never go stale. "
        "See [Collections](/cli/collections) for what each list is.",
        "",
        f"Browse by difficulty: {intro_links}.",
        "",
    ]
    index_rows = [
        f"| [All Problems](/catalog/all) | {len(problems)} "
        f"| {total_split['Easy']} | {total_split['Medium']} | {total_split['Hard']} |"
    ]
    for tag, names in collections.items():
        split = difficulty_split(names, problems)
        display = COLLECTION_META[tag]["label"]
        index_rows.append(
            f"| [{display}](/catalog/{tag}) | {len(names)} "
            f"| {split['Easy']} | {split['Medium']} | {split['Hard']} |"
        )
    lines += table_div(["Collection", "Problems", "Easy", "Medium", "Hard"], index_rows)
    lines += [
        "",
        "Every problem directory ships the same [six files](/practice/problem-anatomy).",
        "",
    ]
    return "\n".join(lines)


def render_count_patches(total: int) -> dict[Path, str]:
    patches: dict[Path, str] = {}
    for rel, (start, end) in COUNT_FILES.items():
        path = REPO_ROOT / rel
        pattern = re.compile(re.escape(start) + r"(.*?)" + re.escape(end), re.DOTALL)
        text = path.read_text()
        if not pattern.search(text):
            print(f"❌ {rel} is missing problem-count markers ({start})")
            sys.exit(1)
        patches[path] = pattern.sub(f"{start}{total}{end}", text)
    return patches


def render_all() -> dict[Path, str]:
    tags = load_tags()
    problems = load_problems()

    seo_titles = [meta["title"] for meta in COLLECTION_META.values()] + [
        ALL_PAGE_TITLE,
        INDEX_PAGE_TITLE,
        *DIFFICULTY_TITLES.values(),
    ]
    assert len(set(seo_titles)) == len(seo_titles), "collection titles must be unique"
    assert all(len(t) <= 46 for t in seo_titles), (
        f"SEO titles must stay <= 46 chars (Mintlify appends ' - leetcode-py'): "
        f"{[t for t in seo_titles if len(t) > 46]}"
    )

    missing = [
        (tag, name)
        for tag, names in tags.items()
        for name in resolve_tag(tags, tag)
        if name not in problems
    ]
    if missing:
        print(f"❌ Collection tags reference unknown problems: {missing}")
        sys.exit(1)

    collections = {tag: resolve_tag(tags, tag) for tag in tags}

    pages: dict[Path, str] = {
        CATALOG_DIR / "index.mdx": render_index_page(collections, problems),
    }
    pages.update(render_all_pages(problems))
    pages.update(render_difficulty_pages(problems))
    for tag, names in collections.items():
        pages.update(render_collection_page(tag, names, problems, tags))
    pages.update(render_count_patches(len(problems)))
    # End every file at exactly one newline so pre-commit's end-of-file-fixer
    # agrees with regeneration (JSX-wrapped tables otherwise end in a blank
    # line, and the fixer and lint hook would fight over it forever).
    return {path: content.rstrip("\n") + "\n" for path, content in pages.items()}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated pages against disk, exit 1 on drift",
    )
    args = parser.parse_args()

    pages = render_all()
    expected = set(pages)

    stale = {p for p in CATALOG_DIR.glob("*.mdx") if p not in expected}

    if args.check:
        drift: list[Path] = sorted(stale)
        for path, content in sorted(pages.items()):
            if not path.exists() or path.read_text() != content:
                drift.append(path)
        if drift:
            print("❌ docs/catalog/ is out of date, run: bake lint")
            for path in drift:
                print(f"  {path.relative_to(REPO_ROOT)}")
            sys.exit(1)
        print("✅ docs/catalog/ is up to date")
        return

    CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in sorted(pages.items()):
        path.write_text(content)
    for path in stale:
        path.unlink()
        print(f"Removed stale page: {path.relative_to(REPO_ROOT)}")

    written = sorted(p.name for p in pages)
    print(f"✅ Generated {len(written)} pages into docs/catalog/ ({', '.join(written)})")


if __name__ == "__main__":
    main()
