#!/usr/bin/env python3
"""Generate docs/catalog/ pages from the JSON problem templates.

Output is deterministic: same tags.json5 + problems/*.json in, same mdx out.
Run with --check to verify committed pages are up to date without writing.
"""

import argparse
import json
import sys
from pathlib import Path

import json5

REPO_ROOT = Path(__file__).resolve().parent.parent
TAGS_FILE = REPO_ROOT / "src/leetcode_py/cli/resources/leetcode/json/tags.json5"
PROBLEMS_DIR = REPO_ROOT / "src/leetcode_py/cli/resources/leetcode/json/problems"
CATALOG_DIR = REPO_ROOT / "docs/catalog"

GENERATED_HEADER = "{/* GENERATED by scripts/gen_catalog.py - do not edit */}"
GITHUB_BASE = "https://github.com/wislertt/leetcode-py/blob/main/leetcode"

# Display name per collection tag. Order follows tags.json5. Origin links
# live on the hand-written Collections page, not here.
COLLECTION_META: dict[str, str] = {
    "grind-75": "Grind 75",
    "grind": "Grind",
    "blind-75": "Blind 75",
    "neetcode-150": "NeetCode 150",
    "neetcode-250": "NeetCode 250",
    "neetcode": "NeetCode All",
    "algo-master-75": "AlgoMaster 75",
}

DIFFICULTIES = ["Easy", "Medium", "Hard"]


def load_tags() -> dict[str, list]:
    with open(TAGS_FILE) as f:
        return json5.load(f)


def load_problems() -> dict[str, dict]:
    problems: dict[str, dict] = {}
    for json_file in sorted(PROBLEMS_DIR.glob("*.json")):
        with open(json_file) as f:
            data = json.load(f)
        problems[data["problem_name"]] = {
            "number": int(data["problem_number"]),
            "title": data["problem_title"],
            "difficulty": data["difficulty"],
        }
    return problems


def resolve_tag(tags: dict[str, list], tag: str) -> list[str]:
    """Expand a tag list, following {"tag": ...} includes, dedup in order."""
    problems: list[str] = []
    for item in tags[tag]:
        if isinstance(item, dict):
            for name in resolve_tag(tags, item["tag"]):
                if name not in problems:
                    problems.append(name)
        elif item not in problems:
            problems.append(item)
    return problems


def tag_includes(tags: dict[str, list], tag: str) -> list[str]:
    return [item["tag"] for item in tags[tag] if isinstance(item, dict) and "tag" in item]


def difficulty_split(names: list[str], problems: dict[str, dict]) -> dict[str, int]:
    split = dict.fromkeys(DIFFICULTIES, 0)
    for name in names:
        split[problems[name]["difficulty"]] += 1
    return split


def problem_url(name: str) -> str:
    return f"{GITHUB_BASE}/{name}/README.md"


def solution_url(name: str) -> str:
    return f"{GITHUB_BASE}/{name}/solution.py"


def split_phrase(split: dict[str, int]) -> str:
    return ", ".join(f"{split[d]} {d}" for d in DIFFICULTIES if split[d])


def render_collection_page(
    tag: str,
    names: list[str],
    problems: dict[str, dict],
    tags: dict[str, list],
) -> str:
    display = COLLECTION_META[tag]
    split = difficulty_split(names, problems)
    includes = tag_includes(tags, tag)
    rows = sorted(names, key=lambda n: problems[n]["number"])

    include_line = ""
    if includes:
        parts = [f"[{COLLECTION_META[ref]}](/catalog/{ref})" for ref in includes]
        include_line = f"\nThis collection includes every problem in {', '.join(parts)}.\n"

    description = f"All {len(names)} {display} problems with links to each problem and solution."

    lines = [
        "---",
        f"title: {display}",
        f"description: {description}",
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"{display} holds {len(names)} problems ({split_phrase(split)}).",
        include_line,
        "Generate the whole collection into the current directory:",
        "",
        "```bash",
        f"lcpy gen -t {tag}",
        "```",
        "",
        "| # | Problem | Difficulty | Solution |",
        "| --- | --- | --- | --- |",
    ]
    for name in rows:
        p = problems[name]
        lines.append(
            f"| {p['number']} | [{p['title']}]({problem_url(name)}) "
            f"| {p['difficulty']} | [solution.py]({solution_url(name)}) |"
        )
    lines.append("")
    return "\n".join(lines)


def render_all_page(
    collections: dict[str, list[str]],
    problems: dict[str, dict],
) -> str:
    split = difficulty_split(list(problems), problems)
    lines = [
        "---",
        "title: All Problems",
        f"description: All {len(problems)} problems with difficulty, collections, and links.",
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"Every problem shipped in this repository: {len(problems)} problems "
        f"({split_phrase(split)}).",
        "",
        "Generate every problem directory into the current directory:",
        "",
        "```bash",
        "lcpy gen --all",
        "```",
        "",
        "| # | Problem | Difficulty | Collections | Solution |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in sorted(problems, key=lambda n: problems[n]["number"]):
        p = problems[name]
        member_of = (
            ", ".join(COLLECTION_META[tag] for tag, names in collections.items() if name in names)
            or "-"
        )
        lines.append(
            f"| {p['number']} | [{p['title']}]({problem_url(name)}) "
            f"| {p['difficulty']} | {member_of} | [solution.py]({solution_url(name)}) |"
        )
    lines.append("")
    return "\n".join(lines)


def render_index_page(
    collections: dict[str, list[str]],
    problems: dict[str, dict],
) -> str:
    total_split = difficulty_split(list(problems), problems)

    lines = [
        "---",
        "title: Catalog",
        "description: Every problem in every collection, generated from the JSON templates.",
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"All {len(problems)} problems across {len(collections)} collections, "
        "generated straight from the templates so counts never go stale. "
        "See [Collections](/cli/collections) for what each list is.",
        "",
        "| Collection | Problems | Easy | Medium | Hard |",
        "| --- | --- | --- | --- | --- |",
        f"| [All Problems](/catalog/all) | {len(problems)} "
        f"| {total_split['Easy']} | {total_split['Medium']} | {total_split['Hard']} |",
    ]
    for tag, names in collections.items():
        display = COLLECTION_META[tag]
        split = difficulty_split(names, problems)
        lines.append(
            f"| [{display}](/catalog/{tag}) | {len(names)} "
            f"| {split['Easy']} | {split['Medium']} | {split['Hard']} |"
        )

    lines += [
        "",
        "Every problem directory ships the same [six files](/practice/problem-anatomy).",
        "",
    ]
    return "\n".join(lines)


def render_all() -> dict[Path, str]:
    tags = load_tags()
    problems = load_problems()

    missing = [
        (tag, name)
        for tag, names in tags.items()
        for name in resolve_tag(tags, tag)
        if name not in problems
    ]
    if missing:
        print(f"❌ Collection tags reference unknown problems: {missing}")
        sys.exit(1)

    collections = {tag: resolve_tag(tags, tag) for tag in tags}

    pages: dict[Path, str] = {
        CATALOG_DIR / "index.mdx": render_index_page(collections, problems),
        CATALOG_DIR / "all.mdx": render_all_page(collections, problems),
    }
    for tag, names in collections.items():
        pages[CATALOG_DIR / f"{tag}.mdx"] = render_collection_page(tag, names, problems, tags)
    return pages


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated pages against disk, exit 1 on drift",
    )
    args = parser.parse_args()

    pages = render_all()
    expected = set(pages)

    stale = {p for p in CATALOG_DIR.glob("*.mdx") if p not in expected}

    if args.check:
        drift: list[Path] = sorted(stale)
        for path, content in sorted(pages.items()):
            if not path.exists() or path.read_text() != content:
                drift.append(path)
        if drift:
            print("❌ docs/catalog/ is out of date, run: bake docs-catalog")
            for path in drift:
                print(f"  {path.relative_to(REPO_ROOT)}")
            sys.exit(1)
        print("✅ docs/catalog/ is up to date")
        return

    CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in sorted(pages.items()):
        path.write_text(content)
    for path in stale:
        path.unlink()
        print(f"Removed stale page: {path.relative_to(REPO_ROOT)}")

    written = sorted(p.name for p in pages)
    print(f"✅ Generated {len(written)} pages into docs/catalog/ ({', '.join(written)})")


if __name__ == "__main__":
    main()
