#!/usr/bin/env python3
"""Generate docs/problems/ pages from the JSON templates and solutions.

Each page lives at /problems/<kebab-slug>/ (out of nav, sitemap-only via
seo.indexing in docs.json). Output is deterministic: same JSON + solution.py
in, same mdx out.

PoC stage: pass --only <problem_name> (repeatable) to generate a subset.
"""

import argparse
import json
import re
import sys
from pathlib import Path

import json5
from gen_catalog import COLLECTION_META

REPO_ROOT = Path(__file__).resolve().parent.parent
TAGS_FILE = REPO_ROOT / "src/leetcode_py/cli/resources/leetcode/json/tags.json5"
PROBLEMS_DIR = REPO_ROOT / "src/leetcode_py/cli/resources/leetcode/json/problems"
PROBLEMS_DOCS_DIR = REPO_ROOT / "docs/problems"

GENERATED_HEADER = "{/* GENERATED by scripts/gen_problems.py - do not edit */}"
GITHUB_BASE = "https://github.com/wislertt/leetcode-py/blob/main/leetcode"
LEETCODE_BASE = "https://leetcode.com/problems"

TITLE_SUFFIXES = (" Python Solution with Tests", " Python Solution")
DESCRIPTION_LIMIT = 120  # keeps 307 entries under the llms.txt 100k cap


def kebab(name: str) -> str:
    return name.replace("_", "-")


def mdx_escape(text: str) -> str:
    """Escape JSX-significant characters (<, {, }) so raw MDX compiles.

    Fenced blocks and inline code spans stay verbatim: character references
    like &lt; render literally inside code, not as the character."""
    parts = re.split(r"(```.*?```|`[^`\n]*`)", text, flags=re.DOTALL)
    for i, part in enumerate(parts):
        if part.startswith("`"):
            continue
        parts[i] = part.replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;")
    return "".join(parts)


def load_tags() -> dict[str, list]:
    with open(TAGS_FILE) as f:
        return json5.load(f)


def resolve_tag(tags: dict[str, list], tag: str) -> list[str]:
    problems: list[str] = []
    for item in tags[tag]:
        if isinstance(item, dict):
            for name in resolve_tag(tags, item["tag"]):
                if name not in problems:
                    problems.append(name)
        elif item not in problems:
            problems.append(item)
    return problems


def load_problems() -> dict[str, dict]:
    problems: dict[str, dict] = {}
    for json_file in sorted(PROBLEMS_DIR.glob("*.json")):
        with open(json_file) as f:
            data = json.load(f)
        problems[data["problem_name"]] = data
    return problems


def collections_for(name: str, tags: dict[str, list]) -> list[str]:
    return [tag for tag in tags if name in resolve_tag(tags, tag)]


def page_title(problem_title: str) -> str:
    """Long LeetCode names overflow the 46-char cap, so fall back tier by
    tier: short names get the full query-shaped formula, medium names a
    shorter suffix, long names the bare title, extreme names a word-boundary
    truncation. Uniqueness + length are asserted in render_pages."""
    for suffix in TITLE_SUFFIXES:
        if len(problem_title) + len(suffix) <= 46:
            return f"{problem_title}{suffix}"
    if len(problem_title) <= 46:
        return problem_title
    cut = problem_title[:46]
    return cut[: cut.rfind(" ")].rstrip(" ,-")


def page_description(number: str, case_count: int) -> str:
    """Standalone description: no title repeat, the SERP already shows it."""
    description = (
        f"Tested Python solution for LeetCode {number} with {case_count} pytest "
        "cases. Generate a practice environment with lcpy."
    )
    if len(description) > DESCRIPTION_LIMIT:
        description = f"Tested Python solution for LeetCode {number} with a pytest suite."
    return description


def count_cases(data: dict) -> int:
    return sum(len(method["test_cases"]["list"]) for method in data["_test_methods"]["list"])


def parse_complexity(solution_src: str) -> dict[str, str]:
    time = re.search(r"#\s*Time:\s*(.+)", solution_src)
    space = re.search(r"#\s*Space:\s*(.+)", solution_src)
    return {
        "time": time.group(1).strip() if time else "",
        "space": space.group(1).strip() if space else "",
    }


def validate_mdx(content: str) -> None:
    """Raw < { } outside code fences and MDX comments break compilation."""
    in_fence = False
    for line in content.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or line.lstrip().startswith("{/*"):
            continue
        prose = re.sub(r"`[^`]*`", "", line)
        assert "<" not in prose and "{" not in prose and "}" not in prose, (
            f"unescaped JSX character in: {line}"
        )


def render_problem_page(
    name: str,
    data: dict,
    tags: dict[str, list],
    solution_src: str,
) -> str:
    slug = kebab(name)
    title = page_title(data["problem_title"])
    difficulty = data["difficulty"]
    topics = data["topics"]
    complexity = parse_complexity(solution_src)
    collections = collections_for(name, tags)

    lines = [
        "---",
        f'title: "{title}"',
        f'description: "{page_description(data["problem_number"], count_cases(data))}"',
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"LeetCode {data['problem_number']}, {difficulty}. Topics: {topics}. "
        f"[View on LeetCode]({LEETCODE_BASE}/{slug}/description/).",
        "",
        "Generate this problem as a practice environment: tested reference "
        f"solution, {count_cases(data)} [parametrized pytest cases]"
        "(/practice/testing), and a playground notebook:",
        "",
        "```bash",
        f"lcpy gen -n {data['problem_number']}   # by problem number",
        f"lcpy gen -s {name}   # by problem name",
        "```",
        "",
        "## Problem",
        "",
        mdx_escape(data["readme_description"]),
        "",
        "### Examples",
        "",
    ]
    for example in data["_readme_examples"]["list"]:
        lines += [mdx_escape(example["content"]), ""]

    lines += ["### Constraints", "", mdx_escape(data["readme_constraints"]), ""]
    if data.get("readme_additional"):
        lines += [mdx_escape(data["readme_additional"]), ""]

    lines += [
        "## Solution",
        "",
        f"Reference implementation from [solution.py on GitHub]({GITHUB_BASE}/{name}/solution.py), "
        f"full suite in [test_solution.py]({GITHUB_BASE}/{name}/test_solution.py):",
        "",
        "```python",
        solution_src.rstrip("\n"),
        "```",
        "",
        "## Complexity",
        "",
        "| Time | Space |",
        "| --- | --- |",
        f"| {mdx_escape(complexity['time']) or '-'} | {mdx_escape(complexity['space']) or '-'} |",
        "",
        "## Tags",
        "",
    ]
    if collections:
        lines.append(
            ", ".join(f"[{COLLECTION_META[tag]['label']}](/catalog/{tag})" for tag in collections)
            + "."
        )
    lines.append("")
    return "\n".join(lines)


def render_pages(names: list[str]) -> dict[Path, str]:
    tags = load_tags()
    problems = load_problems()

    titles = [page_title(p["problem_title"]) for p in problems.values()]
    assert len(set(titles)) == len(titles), (
        f"problem page titles must be unique: {sorted(t for t in titles if titles.count(t) > 1)}"
    )
    assert all(len(t) <= 46 for t in titles), (
        f"titles must stay <= 46 chars (Mintlify appends ' - leetcode-py'): "
        f"{[t for t in titles if len(t) > 46]}"
    )

    pages: dict[Path, str] = {}
    for name in names:
        data = problems[name]
        solution_src = (REPO_ROOT / "leetcode" / name / "solution.py").read_text()
        pages[PROBLEMS_DOCS_DIR / f"{kebab(name)}.mdx"] = render_problem_page(
            name, data, tags, solution_src
        )
    for content in pages.values():
        validate_mdx(content)
    return pages


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--only",
        action="append",
        default=[],
        metavar="PROBLEM_NAME",
        help="Generate only the named problem(s); default is all",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated pages against disk, exit 1 on drift",
    )
    args = parser.parse_args()

    names = args.only or sorted(load_problems())
    unknown = [n for n in names if (PROBLEMS_DIR / f"{n}.json").exists() is False]
    if unknown:
        print(f"❌ Unknown problem names: {unknown}")
        sys.exit(1)

    pages = render_pages(names)

    if args.check:
        drift = [
            path
            for path, content in sorted(pages.items())
            if not path.exists() or path.read_text() != content
        ]
        if drift:
            print("❌ docs/problems/ is out of date, regenerate with this script")
            for path in drift:
                print(f"  {path.relative_to(REPO_ROOT)}")
            sys.exit(1)
        print(f"✅ {len(pages)} problem page(s) up to date")
        return

    PROBLEMS_DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in sorted(pages.items()):
        path.write_text(content)
    print(f"✅ Generated {len(pages)} page(s) into docs/problems/")


if __name__ == "__main__":
    main()
