import pytest

from leetcode_py import logged_test

from .helpers import assert_wiggle_max_length, run_wiggle_max_length
from .solution import Solution


class TestWiggleSubsequence:
    def setup_method(self):
        self.solution = Solution()

    @logged_test
    @pytest.mark.parametrize(
        "nums, expected",
        [
            ([1, 7, 4, 9, 2, 5], 6),
            ([1, 17, 5, 10, 13, 15, 10, 5, 16, 8], 7),
            ([1, 2, 3, 4, 5, 6, 7, 8, 9], 2),
            ([9, 8, 7, 6, 5], 2),
            ([5], 1),
            ([1, 2], 2),
            ([2, 2], 1),
            ([3, 3, 3, 3], 1),
            ([1, 2, 2, 1], 3),
            ([0, 0, 0, 1, 0, 1, 0], 5),
            ([1, 5, 5, 5, 3, 6, 6, 2], 5),
            ([10, 22, 9, 33, 49, 50, 31, 60], 6),
            (
                [
                    7,
                    3,
                    7,
                    6,
                    0,
                    9,
                    4,
                    5,
                    2,
                    2,
                    9,
                    6,
                    8,
                    5,
                    4,
                    9,
                    4,
                    5,
                    1,
                    6,
                    9,
                    3,
                    9,
                    7,
                    1,
                    7,
                    0,
                    3,
                    9,
                    2,
                    1,
                    7,
                    4,
                    7,
                    7,
                    1,
                ],
                28,
            ),
            ([9, 6, 7, 8, 8, 1, 0, 4, 0, 3, 6, 9, 9, 3, 7, 3, 9, 1, 5, 3, 5, 0, 0, 2, 2, 9, 2], 18),
            (
                [
                    2,
                    2,
                    2,
                    7,
                    3,
                    3,
                    8,
                    6,
                    3,
                    8,
                    5,
                    5,
                    8,
                    7,
                    8,
                    5,
                    8,
                    4,
                    8,
                    3,
                    1,
                    7,
                    0,
                    6,
                    9,
                    2,
                    9,
                    7,
                    3,
                    3,
                    1,
                    9,
                    4,
                    0,
                    8,
                ],
                24,
            ),
            ([9, 8, 3, 8, 5, 4, 3, 5, 5, 4, 5, 9, 3, 0, 2, 4, 5, 0, 8, 9, 8, 3, 5, 8], 13),
            (
                [
                    3,
                    1,
                    5,
                    8,
                    6,
                    9,
                    0,
                    5,
                    9,
                    1,
                    2,
                    3,
                    0,
                    8,
                    2,
                    3,
                    8,
                    7,
                    4,
                    4,
                    5,
                    9,
                    1,
                    0,
                    6,
                    0,
                    8,
                    0,
                ],
                20,
            ),
            ([2, 9, 6, 9, 3, 4, 8, 5, 6, 9, 8, 4, 2, 0, 3, 6, 5, 4, 4, 2, 5, 7, 0, 1, 9, 4], 15),
        ],
    )
    def test_wiggle_max_length(self, nums: list[int], expected: int):
        result = run_wiggle_max_length(Solution, nums)
        assert_wiggle_max_length(result, expected)
