import pytest

from leetcode_py import logged_test

from .helpers import assert_circular_deque, run_circular_deque
from .solution import MyCircularDeque


class TestDesignCircularDeque:
    @logged_test
    @pytest.mark.parametrize(
        "operations, inputs, expected",
        [
            (
                [
                    "MyCircularDeque",
                    "insert_last",
                    "insert_last",
                    "insert_front",
                    "insert_front",
                    "get_rear",
                    "is_full",
                    "delete_last",
                    "insert_front",
                    "get_front",
                ],
                [[3], [1], [2], [3], [4], [], [], [], [4], []],
                [None, True, True, True, False, 2, True, True, True, 4],
            ),
            (
                [
                    "MyCircularDeque",
                    "get_front",
                    "get_rear",
                    "is_empty",
                    "is_full",
                    "delete_front",
                    "delete_last",
                    "is_empty",
                ],
                [[3], [], [], [], [], [], [], []],
                [None, -1, -1, True, False, False, False, True],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "is_full",
                    "insert_last",
                    "get_front",
                    "get_rear",
                    "delete_front",
                    "is_empty",
                    "insert_last",
                    "get_front",
                ],
                [[1], [5], [], [6], [], [], [], [], [7], []],
                [None, True, True, False, 5, 5, True, True, True, 7],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_last",
                    "insert_last",
                    "insert_last",
                    "delete_front",
                    "delete_front",
                    "insert_last",
                    "insert_last",
                    "is_full",
                    "insert_last",
                    "get_front",
                    "get_rear",
                ],
                [[3], [1], [2], [3], [], [], [4], [5], [], [6], [], []],
                [None, True, True, True, True, True, True, True, True, False, 3, 5],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "insert_front",
                    "insert_front",
                    "delete_last",
                    "insert_front",
                    "get_front",
                    "get_rear",
                    "is_full",
                ],
                [[3], [1], [2], [3], [], [4], [], [], []],
                [None, True, True, True, True, True, 4, 2, True],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "insert_last",
                    "insert_front",
                    "insert_last",
                    "is_full",
                    "get_front",
                    "get_rear",
                    "delete_front",
                    "delete_last",
                    "get_front",
                    "get_rear",
                    "is_empty",
                ],
                [[3], [10], [20], [30], [40], [], [], [], [], [], [], [], []],
                [None, True, True, True, False, True, 30, 20, True, True, 10, 10, False],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "get_front",
                    "get_rear",
                    "delete_last",
                    "is_empty",
                    "insert_last",
                    "get_rear",
                ],
                [[3], [0], [], [], [], [], [0], []],
                [None, True, 0, 0, True, True, True, 0],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_last",
                    "insert_front",
                    "is_full",
                    "get_front",
                    "get_rear",
                    "delete_front",
                    "get_front",
                ],
                [[1000], [999], [0], [], [], [], [], []],
                [None, True, True, False, 0, 999, True, 999],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_last",
                    "insert_last",
                    "delete_front",
                    "delete_front",
                    "insert_front",
                    "insert_front",
                    "insert_front",
                    "get_front",
                    "get_rear",
                ],
                [[3], [1], [2], [], [], [3], [4], [5], [], []],
                [None, True, True, True, True, True, True, True, 5, 3],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "delete_last",
                    "delete_last",
                    "insert_last",
                    "insert_last",
                    "get_front",
                    "get_rear",
                    "delete_front",
                    "get_front",
                ],
                [[3], [1], [], [], [2], [3], [], [], [], []],
                [None, True, True, False, True, True, 2, 3, True, 3],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_last",
                    "insert_last",
                    "delete_front",
                    "insert_last",
                    "delete_front",
                    "insert_last",
                    "get_front",
                    "get_rear",
                    "is_full",
                    "delete_last",
                    "delete_last",
                    "is_empty",
                ],
                [[2], [1], [2], [], [3], [], [4], [], [], [], [], [], []],
                [None, True, True, True, True, True, True, 3, 4, True, True, True, True],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "insert_front",
                    "get_front",
                    "delete_front",
                    "get_front",
                    "delete_front",
                    "delete_front",
                ],
                [[3], [1], [2], [], [], [], [], []],
                [None, True, True, 2, True, 1, True, False],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_last",
                    "insert_last",
                    "get_rear",
                    "delete_last",
                    "get_rear",
                    "delete_last",
                    "delete_last",
                ],
                [[3], [1], [2], [], [], [], [], []],
                [None, True, True, 2, True, 1, True, False],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "insert_last",
                    "insert_front",
                    "insert_last",
                    "get_front",
                    "get_rear",
                    "delete_front",
                    "insert_front",
                    "insert_front",
                    "get_front",
                    "get_rear",
                ],
                [[3], [1], [2], [3], [4], [], [], [], [5], [6], [], []],
                [None, True, True, True, False, 3, 2, True, True, False, 5, 2],
            ),
            (
                [
                    "MyCircularDeque",
                    "insert_front",
                    "delete_front",
                    "insert_front",
                    "get_front",
                    "delete_last",
                    "insert_last",
                    "get_rear",
                    "is_full",
                    "is_empty",
                ],
                [[1], [9], [], [8], [], [], [7], [], [], []],
                [None, True, True, True, 8, True, True, 7, True, False],
            ),
            (
                [
                    "MyCircularDeque",
                    "is_empty",
                    "insert_last",
                    "is_empty",
                    "insert_front",
                    "is_full",
                    "insert_last",
                    "is_full",
                    "get_front",
                    "get_rear",
                    "delete_last",
                    "insert_front",
                    "get_rear",
                ],
                [[3], [], [5], [], [6], [], [7], [], [], [], [], [8], []],
                [None, True, True, False, True, False, True, True, 6, 7, True, True, 5],
            ),
        ],
    )
    def test_circular_deque(
        self, operations: list[str], inputs: list[list[int]], expected: list[int | bool | None]
    ):
        result, _ = run_circular_deque(MyCircularDeque, operations, inputs)
        assert_circular_deque(result, expected)
